<?php

namespace Database\Seeders;

use App\Models\V1\Libraries\LibKonsultaMedicineForm;
use Illuminate\Database\Seeder;

class LibKonsultaMedicineFormSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        LibKonsultaMedicineForm::upsert([
            ['code' => '00000', 'desc' => ''],
            ['code' => 'AERO1', 'desc' => 'AEROSOL POWDER'],
            ['code' => 'AERO2', 'desc' => 'AEROSOL SPRAY'],
            ['code' => 'AERO3', 'desc' => 'AEROSOL'],
            ['code' => 'AEROS', 'desc' => 'AEROSOL METERED'],
            ['code' => 'BAM01', 'desc' => 'BREATH ACTUATED MDI'],
            ['code' => 'BARCH', 'desc' => 'BAR CHEWABLE'],
            ['code' => 'BEAD1', 'desc' => 'BEAD IMPLANT SUSTAINED RELEASE'],
            ['code' => 'BEAD2', 'desc' => 'BEAD'],
            ['code' => 'BEADI', 'desc' => 'BEAD IMPLANT EXTENDED RELEASE'],
            ['code' => 'BLOCK', 'desc' => 'BLOCK'],
            ['code' => 'BREAD', 'desc' => 'BREADSTICK'],
            ['code' => 'BULKX', 'desc' => 'BULK'],
            ['code' => 'CAP10', 'desc' => 'CAPSULE COATED'],
            ['code' => 'CAP11', 'desc' => 'CAPSULE COATED PELLETS'],
            ['code' => 'CAP12', 'desc' => 'CAPSULE DELAYED ACTION COATED HARD GELATIN'],
            ['code' => 'CAP13', 'desc' => 'CAPSULE DELAYED ACTION COATED'],
            ['code' => 'CAP14', 'desc' => 'CAPSULE DELAYED ACTION ENTERIC COATED HARD GELATIN'],
            ['code' => 'CAP15', 'desc' => 'CAPSULE DELAYED ACTION ENTERIC COATED SOFT GELATIN'],
            ['code' => 'CAP16', 'desc' => 'CAPSULE DELAYED ACTION ENTERIC COATED'],
            ['code' => 'CAP17', 'desc' => 'CAPSULE DELAYED ACTION HARD GELATIN GELATIN'],
            ['code' => 'CAP18', 'desc' => 'CAPSULE DELAYED ACTION'],
            ['code' => 'CAP19', 'desc' => 'CAPSULE DELAYED RELEASE PELLETS'],
            ['code' => 'CAP20', 'desc' => 'CAPSULE DELAYED RELEASE'],
            ['code' => 'CAP21', 'desc' => 'CAPSULE ENTERIC COATED PELLETS'],
            ['code' => 'CAP22', 'desc' => 'CAPSULE EXTENDED RELEASE'],
            ['code' => 'CAP23', 'desc' => 'CAPSULE FILM COATED EXTENDED RELEASE'],
            ['code' => 'CAP24', 'desc' => 'CAPSULE FILM COATED HARD GELATIN'],
            ['code' => 'CAP25', 'desc' => 'CAPSULE FILM COATED'],
            ['code' => 'CAP26', 'desc' => 'CAPSULE FOR MICROEMULSION'],
            ['code' => 'CAP27', 'desc' => 'CAPSULE GELATIN COATED'],
            ['code' => 'CAP28', 'desc' => 'CAPSULE HARD GELATIN'],
            ['code' => 'CAP29', 'desc' => 'CAPSULE LIQUID FILLED'],
            ['code' => 'CAP30', 'desc' => 'CAPSULE REPEAT ACTION'],
            ['code' => 'CAP31', 'desc' => 'CAPSULE SOFT GELATIN'],
            ['code' => 'CAP33', 'desc' => 'CAPSULE SOFT GELATIN LIQUID-FILLED'],
            ['code' => 'CAP34', 'desc' => 'CAPSULE SUSTAINED ACTION COATED HARD GELATIN'],
            ['code' => 'CAP35', 'desc' => 'CAPSULE SUSTAINED ACTION COATED SOFT GELATIN'],
            ['code' => 'CAP36', 'desc' => 'CAPSULE SUSTAINED ACTION COATED'],
            ['code' => 'CAP37', 'desc' => 'CAPSULE SUSTAINED ACTION FILM COATED HARD GELATIN'],
            ['code' => 'CAP38', 'desc' => 'CAPSULE SUSTAINED ACTION HARD GELATIN'],
            ['code' => 'CAP39', 'desc' => 'CAPSULE SUSTAINED ACTION SOFT GELATIN'],
            ['code' => 'CAP40', 'desc' => 'CAPSULE SUSTAINED ACTION'],
            ['code' => 'CAP41', 'desc' => 'CAPSULE CONTROLLED RELEASE'],
            ['code' => 'CAP42', 'desc' => 'CAPSULE MODIFIED RELEASE'],
            ['code' => 'CAPS1', 'desc' => 'CAPSULE (IMMED./COMP. RELEASE) COATED SOFT GELATIN'],
            ['code' => 'CAPS2', 'desc' => 'CAPSULE (IMMED./COMP. RELEASE) HARD GELATIN'],
            ['code' => 'CAPS3', 'desc' => 'CAPSULE (IMMED./COMP. RELEASE) SOFT GELATIN CHEWABLE'],
            ['code' => 'CAPS4', 'desc' => 'CAPSULE (IMMED./COMP. RELEASE) SOFT GELATIN PERLE'],
            ['code' => 'CAPS5', 'desc' => 'CAPSULE (IMMED./COMP. RELEASE) SOFT GELATIN'],
            ['code' => 'CAPS6', 'desc' => 'CAPSULE (IMMED./COMP. RELEASE)'],
            ['code' => 'CAPS7', 'desc' => 'CAPSULE COATED EXTENDED RELEASE'],
            ['code' => 'CAPS8', 'desc' => 'CAPSULE COATED HARD GELATIN'],
            ['code' => 'CAPS9', 'desc' => 'CAPSULE COATED SOFT GELATIN'],
            ['code' => 'CAPSU', 'desc' => 'CAPSULE'],
            ['code' => 'CATHE', 'desc' => 'CATHETER'],
            ['code' => 'CEMEN', 'desc' => 'CEMENT'],
            ['code' => 'CIGAR', 'desc' => 'CIGARETTE'],
            ['code' => 'CLOTH', 'desc' => 'CLOTH'],
            ['code' => 'CONCE', 'desc' => 'CONCENTRATE'],
            ['code' => 'CONEX', 'desc' => 'CONE'],
            ['code' => 'COREX', 'desc' => 'CORE EXTENDED RELEASE'],
            ['code' => 'CREA1', 'desc' => 'CREAM EMULSION SUSTAINED RELEASE'],
            ['code' => 'CREA2', 'desc' => 'CREAM SUPPOSITORY'],
            ['code' => 'CREA3', 'desc' => 'CREAM'],
            ['code' => 'CREAM', 'desc' => 'CREAM AUGMENTED'],
            ['code' => 'CRY00', 'desc' => 'CRYSTALS'],
            ['code' => 'CRYST', 'desc' => 'CRYSTAL'],
            ['code' => 'CULTU', 'desc' => 'CULTURE'],
            ['code' => 'DENTI', 'desc' => 'DENTIFRICE'],
            ['code' => 'DEPOS', 'desc' => 'DEPOSIT'],
            ['code' => 'DEVIC', 'desc' => 'DEVICE'],
            ['code' => 'DIAPH', 'desc' => 'DIAPHRAGM'],
            ['code' => 'DISCX', 'desc' => 'DISC'],
            ['code' => 'DISPE', 'desc' => 'DISPERSIBLE TABLET'],
            ['code' => 'DOUCH', 'desc' => 'DOUCHE'],
            ['code' => 'DPI01', 'desc' => 'DRY POWDER'],
            ['code' => 'DRESS', 'desc' => 'DRESSING'],
            ['code' => 'DROPS', 'desc' => 'DROPS'],
            ['code' => 'DRUGX', 'desc' => 'DRUG DELIVERY SYSTEM'],
            ['code' => 'EDS01', 'desc' => 'EYE DROPS SUSPENSION'],
            ['code' => 'EDS02', 'desc' => 'EYE DROPS SOLUTION'],
            ['code' => 'ELIXI', 'desc' => 'ELIXIR'],
            ['code' => 'EMU01', 'desc' => 'EMULOSION'],
            ['code' => 'EMUL1', 'desc' => 'EMULSION CREAM'],
            ['code' => 'EMUL2', 'desc' => 'EMULSION INJECTION'],
            ['code' => 'EMUL3', 'desc' => 'EMULSION LOTION'],
            ['code' => 'EMUL4', 'desc' => 'EMULSION SHAMPOO'],
            ['code' => 'EMUL5', 'desc' => 'EMULSION'],
            ['code' => 'EMULS', 'desc' => 'EMULSION AEROSOL FOAM'],
            ['code' => 'ENEMA', 'desc' => 'ENEMA'],
            ['code' => 'EXTRA', 'desc' => 'EXTRACT'],
            ['code' => 'EYD01', 'desc' => 'EYE DROPS'],
            ['code' => 'EYO01', 'desc' => 'EYE OINTMENT'],
            ['code' => 'FDP01', 'desc' => 'FREEZE-DRIED POWDER + DILUENT'],
            ['code' => 'FIBER', 'desc' => 'FIBER EXTENDED RELEASE'],
            ['code' => 'FILM1', 'desc' => 'FILM CONTROLLED RELEASE'],
            ['code' => 'FILM2', 'desc' => 'FILM EXTENDED RELEASE'],
            ['code' => 'FILM3', 'desc' => 'FILM SOLUBLE'],
            ['code' => 'FILM4', 'desc' => 'FILM'],
            ['code' => 'FOODX', 'desc' => 'FOOD'],
            ['code' => 'FORM_CODE', 'desc' => 'FORM_DESC'],
            ['code' => 'FORS1', 'desc' => 'FOR SUSPENSION EXTENDED RELEASE'],
            ['code' => 'FORS2', 'desc' => 'FOR SUSPENSION'],
            ['code' => 'FORSX', 'desc' => 'FOR SOLUTION'],
            ['code' => 'FPR01', 'desc' => 'FREEZE-DRIED POWDER +  RECONSTITUTION FLUID'],
            ['code' => 'GASFX', 'desc' => 'GAS FOR INHALATION'],
            ['code' => 'GASXX', 'desc' => 'GAS'],
            ['code' => 'GELDE', 'desc' => 'GEL DENTIFRICE'],
            ['code' => 'GELME', 'desc' => 'GEL METERED'],
            ['code' => 'GELXX', 'desc' => 'GEL'],
            ['code' => 'GENER', 'desc' => 'GENERATOR'],
            ['code' => 'GLOBU', 'desc' => 'GLOBULE'],
            ['code' => 'GRA01', 'desc' => 'GRANULES'],
            ['code' => 'GRA10', 'desc' => 'GRANULE FOR SUSPENSION EXTENDED RELEASE'],
            ['code' => 'GRA11', 'desc' => 'GRANULE FOR SUSPENSION'],
            ['code' => 'GRA12', 'desc' => 'GRANULE'],
            ['code' => 'GRAFT', 'desc' => 'GRAFT'],
            ['code' => 'GRAN1', 'desc' => 'GRANULE EFFERVESCENT FOR SOLUTION'],
            ['code' => 'GRAN2', 'desc' => 'GRANULE EFFERVESCENT FOR SUSPENSION'],
            ['code' => 'GRAN3', 'desc' => 'GRANULE EFFERVESCENT'],
            ['code' => 'GRAN4', 'desc' => 'GRANULE ENTERIC COATED'],
            ['code' => 'GRAN5', 'desc' => 'GRANULE FOR ORAL SOLUTION'],
            ['code' => 'GRAN6', 'desc' => 'GRANULE FOR ORAL SUSPENSION'],
            ['code' => 'GRAN7', 'desc' => 'GRANULE FOR RECONSTITUTION CR'],
            ['code' => 'GRAN8', 'desc' => 'GRANULE FOR RECONSTITUTION'],
            ['code' => 'GRAN9', 'desc' => 'GRANULE FOR SOLUTION'],
            ['code' => 'GRANU', 'desc' => 'GRANULE DELAYED RELEASE'],
            ['code' => 'GUMC1', 'desc' => 'GUM CHEWING'],
            ['code' => 'GUMC2', 'desc' => 'GUM RESIN'],
            ['code' => 'GUMCH', 'desc' => 'GUM CHEWING MEDICATED'],
            ['code' => 'GUMXX', 'desc' => 'GUM'],
            ['code' => 'IMPLA', 'desc' => 'IMPLANT'],
            ['code' => 'INFUS', 'desc' => 'INFUSION'],
            ['code' => 'INHA1', 'desc' => 'INHALATION'],
            ['code' => 'INHAL', 'desc' => 'INHALANT'],
            ['code' => 'INJ10', 'desc' => 'INJECTION POWDER LYOPHILIZED FOR SUSPENSION'],
            ['code' => 'INJ11', 'desc' => 'INJECTION POWDER LYOPHILIZED FOR SUSPENSION EXTENDED RELEASE'],
            ['code' => 'INJ12', 'desc' => 'INJECTION SOLUTION CONCENTRATE'],
            ['code' => 'INJ13', 'desc' => 'INJECTION SOLUTION'],
            ['code' => 'INJ14', 'desc' => 'INJECTION SUSPENSION EXTENDED RELEASE'],
            ['code' => 'INJ15', 'desc' => 'INJECTION SUSPENSION LIPOSOMAL'],
            ['code' => 'INJ16', 'desc' => 'INJECTION SUSPENSION SONICATED'],
            ['code' => 'INJ17', 'desc' => 'INJECTION SUSPENSION'],
            ['code' => 'INJ18', 'desc' => 'INJECTION SUSTAINED ACTION'],
            ['code' => 'INJ19', 'desc' => 'INJECTION'],
            ['code' => 'INJE1', 'desc' => 'INJECTION EMULSION'],
            ['code' => 'INJE2', 'desc' => 'INJECTION LIPID COMPLEX'],
            ['code' => 'INJE3', 'desc' => 'INJECTION LIPOSOMAL'],
            ['code' => 'INJE4', 'desc' => 'INJECTION MICROSPHERES'],
            ['code' => 'INJE5', 'desc' => 'INJECTION POWDER FOR SOLUTION'],
            ['code' => 'INJE6', 'desc' => 'INJECTION POWDER FOR SUSPENSION EXTENDED RELEASE'],
            ['code' => 'INJE7', 'desc' => 'INJECTION POWDER FOR SUSPENSION'],
            ['code' => 'INJE8', 'desc' => 'INJECTION POWDER LYOPHILIZED FOR LIPOSOMAL SUSPENSION'],
            ['code' => 'INJE9', 'desc' => 'INJECTION POWDER LYOPHILIZED FOR SOLUTION'],
            ['code' => 'INJEC', 'desc' => 'INJECTABLE'],
            ['code' => 'INSER', 'desc' => 'INSERT EXTENDED RELEASE'],
            ['code' => 'INSEX', 'desc' => 'INSERT'],
            ['code' => 'INTRA', 'desc' => 'INTRAUTERINE DEVICE'],
            ['code' => 'IRRIG', 'desc' => 'IRRIGANT'],
            ['code' => 'IRRIX', 'desc' => 'IRRIGATION'],
            ['code' => 'JELLY', 'desc' => 'JELLY'],
            ['code' => 'KITXX', 'desc' => 'KIT'],
            ['code' => 'LENSX', 'desc' => 'LENS'],
            ['code' => 'LINER', 'desc' => 'LINER DENTAL'],
            ['code' => 'LINIM', 'desc' => 'LINIMENT'],
            ['code' => 'LIPOS', 'desc' => 'LIPOSOME-ENCAPSULATED'],
            ['code' => 'LIPST', 'desc' => 'LIPSTICK'],
            ['code' => 'LIQU1', 'desc' => 'LIQUID CONCENTRATE'],
            ['code' => 'LIQU2', 'desc' => 'LIQUID EXTENDED RELEASE'],
            ['code' => 'LIQU3', 'desc' => 'LIQUID FOR INHALATION'],
            ['code' => 'LIQU4', 'desc' => 'LIQUID WATER STERILE FOR INJECTION'],
            ['code' => 'LIQU5', 'desc' => 'LIQUID'],
            ['code' => 'LIQUI', 'desc' => 'LIQUID CONCENTRATE INJECTION'],
            ['code' => 'LOLLI', 'desc' => 'LOLLIPOP'],
            ['code' => 'LOTI1', 'desc' => 'LOTION'],
            ['code' => 'LOTI2', 'desc' => 'LOTION/SHAMPOO'],
            ['code' => 'LOTIO', 'desc' => 'LOTION AUGMENTED'],
            ['code' => 'LOZEN', 'desc' => 'LOZENGE'],
            ['code' => 'LPS01', 'desc' => 'LYOPHILIZED POWDER + SOLVENT'],
            ['code' => 'LPS02', 'desc' => 'LYOPHILIZED POWDER + DILUENT'],
            ['code' => 'LPS03', 'desc' => 'LYOPHILIZED POWDER + SOLUTION'],
            ['code' => 'LYP01', 'desc' => 'LYOPHILIZED POWDER'],
            ['code' => 'MDIXX', 'desc' => 'METERED DOSE INHALER'],
            ['code' => 'MICRO', 'desc' => 'MICROCAPSULES FOR INJECTION SUSPENSION STERILE'],
            ['code' => 'MICRX', 'desc' => 'MICRONIZED TABLET'],
            ['code' => 'MINIO', 'desc' => 'MINI-OSMOTIC PUMP'],
            ['code' => 'MISCE', 'desc' => 'MISCELLANEOUS'],
            ['code' => 'MOUTH', 'desc' => 'MOUTHWASH'],
            ['code' => 'MUCIL', 'desc' => 'MUCILAGE'],
            ['code' => 'NAS01', 'desc' => 'NASAL AQUEOUS SOLUTION'],
            ['code' => 'NDS01', 'desc' => 'NASAL DROPS SOLUTION'],
            ['code' => 'NOTAX', 'desc' => 'NOT APPLICABLE'],
            ['code' => 'NS001', 'desc' => 'NASAL SPRAY'],
            ['code' => 'OA001', 'desc' => 'ORAL ANTISEPTIC'],
            ['code' => 'OD000', 'desc' => 'ORAL DROPS'],
            ['code' => 'OILXX', 'desc' => 'OIL'],
            ['code' => 'OINTM', 'desc' => 'OINTMENT AUGMENTED'],
            ['code' => 'OINTX', 'desc' => 'OINTMENT'],
            ['code' => 'OPHTH', 'desc' => 'OPHTHALMIC CONTINUOUS RELEASE CORE UNIT'],
            ['code' => 'OPS01', 'desc' => 'OPHTHALMIC SOLUTION'],
            ['code' => 'OPS02', 'desc' => 'OPHTHALMIC SUSPENSION'],
            ['code' => 'OS001', 'desc' => 'ORAL SOLUTION'],
            ['code' => 'OVULE', 'desc' => 'OVULE'],
            ['code' => 'PACKI', 'desc' => 'PACKING'],
            ['code' => 'PAI01', 'desc' => 'PAINT'],
            ['code' => 'PAST1', 'desc' => 'PASTE'],
            ['code' => 'PAST2', 'desc' => 'PASTILLE'],
            ['code' => 'PASTE', 'desc' => 'PASTE DENTIFRICE'],
            ['code' => 'PATC1', 'desc' => 'PATCH ELECTRICALLY CONTROLLED'],
            ['code' => 'PATC2', 'desc' => 'PATCH EXTENDED RELEASE ELECTRICALLY CONTROLLED'],
            ['code' => 'PATC3', 'desc' => 'PATCH EXTENDED RELEASE'],
            ['code' => 'PATC4', 'desc' => 'PATCH'],
            ['code' => 'PATCH', 'desc' => 'PATCH CONTROLLED RELEASE'],
            ['code' => 'PELL1', 'desc' => 'PELLET IMPLANTABLE'],
            ['code' => 'PELL2', 'desc' => 'PELLET'],
            ['code' => 'PELL3', 'desc' => 'PELLETS COATED EXTENDED RELEASE'],
            ['code' => 'PELLE', 'desc' => 'PELLET IMPLANT'],
            ['code' => 'PILLX', 'desc' => 'PILL'],
            ['code' => 'PLAST', 'desc' => 'PLASTER'],
            ['code' => 'POULT', 'desc' => 'POULTICE'],
            ['code' => 'POW10', 'desc' => 'POWDER FOR INJECTION SOLUTION LYOPHILIZED'],
            ['code' => 'POW11', 'desc' => 'POWDER FOR INJECTION SOLUTION WITH ADDITIVES'],
            ['code' => 'POW12', 'desc' => 'POWDER FOR INJECTION SOLUTION WITHOUT ADDITIVES'],
            ['code' => 'POW13', 'desc' => 'POWDER FOR INJECTION SOLUTION'],
            ['code' => 'POW14', 'desc' => 'POWDER FOR INJECTION SUSPENSION LYOPHILIZED SUSTAINED ACTION'],
            ['code' => 'POW15', 'desc' => 'POWDER FOR INJECTION SUSPENSION LYOPHILIZED'],
            ['code' => 'POW16', 'desc' => 'POWDER FOR INJECTION SUSPENSION SUSTAINED ACTION'],
            ['code' => 'POW17', 'desc' => 'POWDER FOR INJECTION SUSPENSION'],
            ['code' => 'POW18', 'desc' => 'POWDER FOR OPHTHALMIC SOLUTION'],
            ['code' => 'POW19', 'desc' => 'POWDER FOR ORAL SOLUTION'],
            ['code' => 'POW20', 'desc' => 'POWDER FOR ORAL SUSPENSION'],
            ['code' => 'POW21', 'desc' => 'POWDER FOR RECONSTITUTION AEROSOL'],
            ['code' => 'POW22', 'desc' => 'POWDER FOR RECONSTITUTION'],
            ['code' => 'POW23', 'desc' => 'POWDER FOR SOLUTION'],
            ['code' => 'POW24', 'desc' => 'POWDER FOR SUSPENSION'],
            ['code' => 'POW25', 'desc' => 'POWDER METERED'],
            ['code' => 'POW26', 'desc' => 'POWDER SPRAY'],
            ['code' => 'POW27', 'desc' => 'POWDER'],
            ['code' => 'POW28', 'desc' => 'POWDER FOR IV INFUSION'],
            ['code' => 'POWD1', 'desc' => 'POWDER AEROSOL'],
            ['code' => 'POWD2', 'desc' => 'POWDER BREATH ACTUATED INHALER'],
            ['code' => 'POWD3', 'desc' => 'POWDER BULK'],
            ['code' => 'POWD4', 'desc' => 'POWDER DENTIFRICE'],
            ['code' => 'POWD5', 'desc' => 'POWDER EXTRACT'],
            ['code' => 'POWD6', 'desc' => 'POWDER FOR INHALATION'],
            ['code' => 'POWD7', 'desc' => 'POWDER FOR INJECTION SOLUTION LYOPHILIZED SUSTAINED ACTION'],
            ['code' => 'POWD8', 'desc' => 'POWDER FOR INJECTION SOLUTION LYOPHILIZED WITH ADDITIVES'],
            ['code' => 'POWD9', 'desc' => 'POWDER FOR INJECTION SOLUTION LYOPHILIZED WITHOUT ADDITIVES'],
            ['code' => 'POWDE', 'desc' => 'POWDER AEROSOL FOR INHALATION'],
            ['code' => 'RESIN', 'desc' => 'RESIN'],
            ['code' => 'RINGX', 'desc' => 'RING'],
            ['code' => 'RINSE', 'desc' => 'RINSE'],
            ['code' => 'RODXX', 'desc' => 'ROD'],
            ['code' => 'ROTAC', 'desc' => 'ROTACAP'],
            ['code' => 'RSOLU', 'desc' => 'RESPIRATORY SOLUTION'],
            ['code' => 'RTU00', 'desc' => 'RECTAL'],
            ['code' => 'SAC01', 'desc' => 'SACHET'],
            ['code' => 'SALVE', 'desc' => 'SALVE'],
            ['code' => 'SHAMP', 'desc' => 'SHAMPOO SUSPENSION'],
            ['code' => 'SHAMX', 'desc' => 'SHAMPOO'],
            ['code' => 'SOAPX', 'desc' => 'SOAP'],
            ['code' => 'SOL10', 'desc' => 'SOLUTION FOR MICROEMULSION'],
            ['code' => 'SOL11', 'desc' => 'SOLUTION FOR SLUSH'],
            ['code' => 'SOL12', 'desc' => 'SOLUTION GEL FORMING EXTENDED RELEASE'],
            ['code' => 'SOL13', 'desc' => 'SOLUTION GEL FORMING/DROPS'],
            ['code' => 'SOL14', 'desc' => 'SOLUTION FOR INJECTION'],
            ['code' => 'SOL15', 'desc' => 'SOLUTION IRRIGATION'],
            ['code' => 'SOL16', 'desc' => 'SOLUTION JUICE'],
            ['code' => 'SOL17', 'desc' => 'SOLUTION LINIMENT'],
            ['code' => 'SOL18', 'desc' => 'SOLUTION LIPOSOME INJECTION'],
            ['code' => 'SOL19', 'desc' => 'SOLUTION LIQUID CONCENTRATE INJECTION'],
            ['code' => 'SOL20', 'desc' => 'SOLUTION LIQUID CONCENTRATE ORAL'],
            ['code' => 'SOL21', 'desc' => 'SOLUTION LIQUID'],
            ['code' => 'SOL22', 'desc' => 'SOLUTION LOTION'],
            ['code' => 'SOL23', 'desc' => 'SOLUTION MODIFIED'],
            ['code' => 'SOL24', 'desc' => 'SOLUTION MOUTHWASH'],
            ['code' => 'SOL25', 'desc' => 'SOLUTION RINSE'],
            ['code' => 'SOL26', 'desc' => 'SOLUTION SHAMPOO'],
            ['code' => 'SOL27', 'desc' => 'SOLUTION SOAP'],
            ['code' => 'SOL28', 'desc' => 'SOLUTION SPRAY METERED PUMP'],
            ['code' => 'SOL29', 'desc' => 'SOLUTION SPRAY'],
            ['code' => 'SOL30', 'desc' => 'SOLUTION SYRUP'],
            ['code' => 'SOL31', 'desc' => 'SOLUTION TINCTURE'],
            ['code' => 'SOL32', 'desc' => 'SOLUTION'],
            ['code' => 'SOL33', 'desc' => 'SOLUTION/DROPS'],
            ['code' => 'SOL34', 'desc' => 'SOLUTION FOR NEBULIZATION'],
            ['code' => 'SOL35', 'desc' => 'SOLUTION FOR INFUSION'],
            ['code' => 'SOL36', 'desc' => 'SOLUTION OF LIDOCAINE'],
            ['code' => 'SOL37', 'desc' => 'EAR DROPS SOLUTION'],
            ['code' => 'SOL38', 'desc' => 'POWDER SOLUTION'],
            ['code' => 'SOL39', 'desc' => 'DEPOT SOLUTION'],
            ['code' => 'SOL40', 'desc' => 'COLLOIDAL SOLUTION'],
            ['code' => 'SOL41', 'desc' => 'TOPICAL SOLUTION'],
            ['code' => 'SOLU1', 'desc' => 'SOLUTION AEROSOL'],
            ['code' => 'SOLU2', 'desc' => 'SOLUTION CONCENTRATE'],
            ['code' => 'SOLU3', 'desc' => 'SOLUTION DENTIFRICE'],
            ['code' => 'SOLU4', 'desc' => 'SOLUTION DOUCHE'],
            ['code' => 'SOLU5', 'desc' => 'SOLUTION DROPS'],
            ['code' => 'SOLU6', 'desc' => 'SOLUTION ELIXIR'],
            ['code' => 'SOLU7', 'desc' => 'SOLUTION ENEMA'],
            ['code' => 'SOLU8', 'desc' => 'SOLUTION EXTRACT'],
            ['code' => 'SOLU9', 'desc' => 'SOLUTION FOR INHALATION'],
            ['code' => 'SOLUB', 'desc' => 'SOLUBLE OBLET'],
            ['code' => 'SOLUT', 'desc' => 'SOLUTION AEROSOL FOR INHALATION'],
            ['code' => 'SOLXX', 'desc' => 'SOL'],
            ['code' => 'SPONG', 'desc' => 'SPONGE'],
            ['code' => 'SPRA1', 'desc' => 'SPRAY METERED PUMP'],
            ['code' => 'SPRA2', 'desc' => 'SPRAY SUSPENSION'],
            ['code' => 'SPRA3', 'desc' => 'SPRAY'],
            ['code' => 'SPRAY', 'desc' => 'SPRAY METERED'],
            ['code' => 'SSC01', 'desc' => 'SURGICAL SKIN CLEANSER'],
            ['code' => 'STICK', 'desc' => 'STICK'],
            ['code' => 'STRI1', 'desc' => 'STRIPS'],
            ['code' => 'STRIP', 'desc' => 'STRIP'],
            ['code' => 'SUPP1', 'desc' => 'SUPPOSITORY EXTENDED RELEASE'],
            ['code' => 'SUPP2', 'desc' => 'SUPPOSITORY INSERT CONTROLLED RELEASE'],
            ['code' => 'SUPP3', 'desc' => 'SUPPOSITORY INSERT'],
            ['code' => 'SUPP4', 'desc' => 'SUPPOSITORY'],
            ['code' => 'SUPPO', 'desc' => 'SUPPOSITORY CONTROLLED RELEASE'],
            ['code' => 'SUS10', 'desc' => 'SUSPENSION SUSTAINED ACTION'],
            ['code' => 'SUS11', 'desc' => 'SUSPENSION SYRUP SUSTAINED ACTION'],
            ['code' => 'SUS12', 'desc' => 'SUSPENSION SYRUP'],
            ['code' => 'SUS13', 'desc' => 'SUSPENSION/DROPS'],
            ['code' => 'SUS14', 'desc' => 'SUSPENSION'],
            ['code' => 'SUSP1', 'desc' => 'SUSPENSION AEROSOL'],
            ['code' => 'SUSP2', 'desc' => 'SUSPENSION DROPS'],
            ['code' => 'SUSP3', 'desc' => 'SUSPENSION ENEMA'],
            ['code' => 'SUSP4', 'desc' => 'SUSPENSION EXTENDED RELEASE'],
            ['code' => 'SUSP5', 'desc' => 'SUSPENSION FOR INHALATION'],
            ['code' => 'SUSP6', 'desc' => 'SUSPENSION INJECTION SUSTAINED ACTION'],
            ['code' => 'SUSP7', 'desc' => 'SUSPENSION INJECTION'],
            ['code' => 'SUSP8', 'desc' => 'SUSPENSION LIQUID MIXTURE'],
            ['code' => 'SUSP9', 'desc' => 'SUSPENSION LIQUID'],
            ['code' => 'SUSPE', 'desc' => 'SUSPENSION AEROSOL FOR INHALATION'],
            ['code' => 'SUTUR', 'desc' => 'SUTURE'],
            ['code' => 'SWABX', 'desc' => 'SWAB'],
            ['code' => 'SYRUP', 'desc' => 'SYRUP'],
            ['code' => 'TAB10', 'desc' => 'TABLET COATED'],
            ['code' => 'TAB11', 'desc' => 'TABLET COATED PARTICLES'],
            ['code' => 'TAB12', 'desc' => 'TABLET CONTROLLED RELEASE'],
            ['code' => 'TAB13', 'desc' => 'TABLET DELAYED ACTION COATED'],
            ['code' => 'TAB14', 'desc' => 'TABLET DELAYED ACTION ENTERIC COATED'],
            ['code' => 'TAB15', 'desc' => 'TABLET DELAYED ACTION'],
            ['code' => 'TAB16', 'desc' => 'TABLET DELAYED RELEASE'],
            ['code' => 'TAB17', 'desc' => 'TABLET DELAYED RELEASE PARTICLES'],
            ['code' => 'TAB18', 'desc' => 'TABLET DISPERSIBLE'],
            ['code' => 'TAB19', 'desc' => 'TABLET EFFERVESCENT FOR SOLUTION'],
            ['code' => 'TAB20', 'desc' => 'TABLET EFFERVESCENT'],
            ['code' => 'TAB21', 'desc' => 'TABLET ENTERIC COATED PARTICLES'],
            ['code' => 'TAB22', 'desc' => 'TABLET EXTENDED RELEASE'],
            ['code' => 'TAB23', 'desc' => 'TABLET FILM COATED EXTENDED RELEASE'],
            ['code' => 'TAB24', 'desc' => 'TABLET FILM COATED'],
            ['code' => 'TAB25', 'desc' => 'TABLET FOR SOLUTION'],
            ['code' => 'TAB26', 'desc' => 'TABLET FOR SUSPENSION'],
            ['code' => 'TAB27', 'desc' => 'TABLET MULTILAYER COATED'],
            ['code' => 'TAB28', 'desc' => 'TABLET MULTILAYER EXTENDED RELEASE'],
            ['code' => 'TAB29', 'desc' => 'TABLET MULTILAYER FILM COATED'],
            ['code' => 'TAB30', 'desc' => 'TABLET MULTILAYER'],
            ['code' => 'TAB31', 'desc' => 'TABLET ORALLY DISINTEGRATING DELAYED RELEASE'],
            ['code' => 'TAB32', 'desc' => 'TABLET ORALLY DISINTEGRATING'],
            ['code' => 'TAB33', 'desc' => 'TABLET REPEAT ACTION COATED'],
            ['code' => 'TAB34', 'desc' => 'TABLET REPEAT ACTION'],
            ['code' => 'TAB35', 'desc' => 'TABLET SOLUBLE'],
            ['code' => 'TAB36', 'desc' => 'TABLET SUGAR COATED'],
            ['code' => 'TAB37', 'desc' => 'TABLET SUSTAINED ACTION COATED'],
            ['code' => 'TAB38', 'desc' => 'TABLET SUSTAINED ACTION FILM COATED'],
            ['code' => 'TAB39', 'desc' => 'TABLET SUSTAINED ACTION MEMBRANE CONTROLLED'],
            ['code' => 'TAB40', 'desc' => 'TABLET SUSTAINED ACTION MULTILAYER COATED'],
            ['code' => 'TAB41', 'desc' => 'TABLET SUSTAINED ACTION MULTILAYER FILM COATED'],
            ['code' => 'TAB42', 'desc' => 'TABLET SUSTAINED ACTION MULTILAYER'],
            ['code' => 'TAB43', 'desc' => 'TABLET SUSTAINED ACTION UNCOATED'],
            ['code' => 'TAB44', 'desc' => 'TABLET SUSTAINED ACTION'],
            ['code' => 'TAB45', 'desc' => 'TABLET SUSTAINED RELEASE FILM COATED'],
            ['code' => 'TAB46', 'desc' => 'TABLET UNCOATED LOZENGE LYOPHILIZED'],
            ['code' => 'TAB47', 'desc' => 'TABLET UNCOATED LOZENGE'],
            ['code' => 'TAB48', 'desc' => 'TABLET UNCOATED TROCHE'],
            ['code' => 'TAB49', 'desc' => 'TABLET'],
            ['code' => 'TAB50', 'desc' => 'TABLET ENTERIC SUGAR COATED'],
            ['code' => 'TAB51', 'desc' => 'TABLET FILM COATED CONTROLLED RELEASE'],
            ['code' => 'TAB52', 'desc' => 'TABLET MODIFIED RELEASE'],
            ['code' => 'TAB53', 'desc' => 'VAGINAL TABLET'],
            ['code' => 'TABL1', 'desc' => 'TABLET (IMMED./COMP. RELEASE) FILM COATED COATED'],
            ['code' => 'TABL2', 'desc' => 'TABLET (IMMED./COMP. RELEASE) MULTILAYER COATED'],
            ['code' => 'TABL3', 'desc' => 'TABLET (IMMED./COMP. RELEASE) MULTILAYER'],
            ['code' => 'TABL4', 'desc' => 'TABLET (IMMED./COMP. RELEASE) SUGAR COATED'],
            ['code' => 'TABL5', 'desc' => 'TABLET (IMMED./COMP. RELEASE) UNCOATED BUCCAL'],
            ['code' => 'TABL6', 'desc' => 'TABLET (IMMED./COMP. RELEASE) UNCOATED CHEWABLE'],
            ['code' => 'TABL7', 'desc' => 'TABLET (IMMED./COMP. RELEASE) UNCOATED EFFERVESCENT'],
            ['code' => 'TABL8', 'desc' => 'TABLET (IMMED./COMP. RELEASE) UNCOATED HYPODERMIC'],
            ['code' => 'TABL9', 'desc' => 'TABLET CHEWABLE'],
            ['code' => 'TABLE', 'desc' => 'TABLET (IMMED./COMP. RELEASE) COATED'],
            ['code' => 'TAMPO', 'desc' => 'TAMPON'],
            ['code' => 'TAPEX', 'desc' => 'TAPE'],
            ['code' => 'TEAXX', 'desc' => 'TEA'],
            ['code' => 'TESTX', 'desc' => 'TEST'],
            ['code' => 'TINCT', 'desc' => 'TINCTURE'],
            ['code' => 'TROCH', 'desc' => 'TROCHE'],
            ['code' => 'TROCX', 'desc' => 'TROCHE/LOZENGE'],
            ['code' => 'USP01', 'desc' => 'USP GRADE'],
            ['code' => 'WAFER', 'desc' => 'WAFER'],
            ['code' => 'WAS01', 'desc' => 'WASH'],
        ], ['code']);
    }
}
