<?php

namespace Database\Seeders;

use App\Models\V1\Libraries\LibKonsultaMedicinePackage;
use Illuminate\Database\Seeder;

class LibKonsultaMedicinePackageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        LibKonsultaMedicinePackage::upsert([
            ['code' => '00000', 'desc' => ''],
            ['code' => '100MB', 'desc' => '100 ML BOTTLE'],
            ['code' => '100ML', 'desc' => '100 ML VIAL'],
            ['code' => '100PC', 'desc' => '100S'],
            ['code' => '105ML', 'desc' => '105 ML BOTTLE'],
            ['code' => '10MLA', 'desc' => '10 ML AMPUL'],
            ['code' => '10MLB', 'desc' => '10 ML BOTTLE'],
            ['code' => '10MLR', 'desc' => '10 ML RESP SOLUTION'],
            ['code' => '10MLV', 'desc' => '10 ML VIAL'],
            ['code' => '10MLX', 'desc' => '10 ML'],
            ['code' => '10PCS', 'desc' => '10S'],
            ['code' => '11PCS', 'desc' => '11S'],
            ['code' => '120MB', 'desc' => '120 ML BOTTLE'],
            ['code' => '120ML', 'desc' => '120 ML'],
            ['code' => '125GA', 'desc' => '1.25 G SACHET'],
            ['code' => '12PCS', 'desc' => '12S'],
            ['code' => '14PCS', 'desc' => '14S'],
            ['code' => '150ML', 'desc' => '150 ML'],
            ['code' => '15MLB', 'desc' => '15 ML BOTTLE'],
            ['code' => '15MLR', 'desc' => '15 ML RESP SOLUTION'],
            ['code' => '15MLV', 'desc' => '15 ML VIAL'],
            ['code' => '15MLX', 'desc' => '15 ML'],
            ['code' => '1MLAM', 'desc' => '1 ML AMPUL'],
            ['code' => '1MLBT', 'desc' => '1 ML BOTTLE'],
            ['code' => '1MLVI', 'desc' => '1 ML VIAL'],
            ['code' => '1THPC', 'desc' => '1000S'],
            ['code' => '200PC', 'desc' => '200S'],
            ['code' => '20MGL', 'desc' => '20 MG/ML AMPULE'],
            ['code' => '20MLR', 'desc' => '20 ML RESP SOLUTION'],
            ['code' => '20MLV', 'desc' => '20 ML VIAL'],
            ['code' => '20PCS', 'desc' => '20S'],
            ['code' => '21PCS', 'desc' => '21S'],
            ['code' => '22MLB', 'desc' => '22 ML BOTTLE'],
            ['code' => '250MB', 'desc' => '250 ML BOTTLE'],
            ['code' => '250ML', 'desc' => '250 ML'],
            ['code' => '25MLA', 'desc' => '2.5 ML AMPULE'],
            ['code' => '25MLB', 'desc' => '2.5 ML BOTTLE'],
            ['code' => '25MLN', 'desc' => '2.5 ML NEBULE'],
            ['code' => '25MLR', 'desc' => '2.5 ML RESP. SOLUTION'],
            ['code' => '25MLV', 'desc' => '25 ML VIAL'],
            ['code' => '25PCS', 'desc' => '25S'],
            ['code' => '2MGBT', 'desc' => '2 MG BOTTLE'],
            ['code' => '2MLAM', 'desc' => '2 ML AMPUL'],
            ['code' => '2MLAV', 'desc' => '2 ML AMPUL/VIAL'],
            ['code' => '2MLBT', 'desc' => '2 ML BOTTLE'],
            ['code' => '2MLNE', 'desc' => '2 ML NEBULE'],
            ['code' => '2MLRS', 'desc' => '2 ML RESP SOLUTION'],
            ['code' => '2MLVI', 'desc' => '2 ML VIAL'],
            ['code' => '2P5ML', 'desc' => '2.5 ML VIAL'],
            ['code' => '30MLB', 'desc' => '30 ML BOTTLE'],
            ['code' => '30MLX', 'desc' => '30 ML'],
            ['code' => '30PCS', 'desc' => '30S'],
            ['code' => '35MLB', 'desc' => '35 ML BOTTLE'],
            ['code' => '39MLB', 'desc' => '39 ML BOTTLE'],
            ['code' => '3MLAM', 'desc' => '3 ML AMPUL'],
            ['code' => '4FLAP', 'desc' => 'BOX OF 4 FLAPS'],
            ['code' => '4MLAG', 'desc' => '4 ML BOTTLE'],
            ['code' => '4MLAM', 'desc' => '4 ML AMPUL'],
            ['code' => '4MLVI', 'desc' => '4 ML VIAL'],
            ['code' => '500PC', 'desc' => '500S'],
            ['code' => '50MLB', 'desc' => '50 ML BOTTLE'],
            ['code' => '50MLV', 'desc' => '50 ML VIAL'],
            ['code' => '50PCS', 'desc' => '50S'],
            ['code' => '5MLAM', 'desc' => '5 ML AMPUL'],
            ['code' => '5MLBT', 'desc' => '5 ML BOTTLE'],
            ['code' => '5MLVI', 'desc' => '5 ML VIAL'],
            ['code' => '5PCSX', 'desc' => '5S'],
            ['code' => '60MLB', 'desc' => '60 ML BOTTLE'],
            ['code' => '60MLS', 'desc' => '60 ML SUSPENSION'],
            ['code' => '60MLV', 'desc' => '60 ML VIAL'],
            ['code' => '60MLX', 'desc' => '60 ML'],
            ['code' => '60PCS', 'desc' => '60S'],
            ['code' => '6MLVX', 'desc' => '6 ML VIAL'],
            ['code' => '6PCSB', 'desc' => '6S'],
            ['code' => '70MLB', 'desc' => '70 ML BOTTLE'],
            ['code' => '75MLB', 'desc' => '75 ML BOTTLE'],
            ['code' => '75MLV', 'desc' => '7.5 ML VIAL'],
            ['code' => '7MLVI', 'desc' => '7 ML VIAL'],
            ['code' => '8PCSX', 'desc' => '8S'],
            ['code' => '9PCSX', 'desc' => '9S'],
            ['code' => 'AM100', 'desc' => 'AMBER BOTTLE OF 100S'],
            ['code' => 'AM25S', 'desc' => 'AMBER BOTTLE OF 25S'],
            ['code' => 'AM500', 'desc' => 'AMBER BOTTLE OF 500S'],
            ['code' => 'AM50S', 'desc' => 'AMBER BOTTLE OF 50S'],
            ['code' => 'AMBGL', 'desc' => 'AMBER GLASS'],
            ['code' => 'AMBOT', 'desc' => 'AMBER BOTTLE'],
            ['code' => 'AMBVI', 'desc' => 'AMBER VIAL'],
            ['code' => 'AMPUL', 'desc' => 'AMPULE'],
            ['code' => 'B1010', 'desc' => 'BLISTER PACK OF 10S (BOX OF 10S)'],
            ['code' => 'B1040', 'desc' => 'BLISTER PACK OF 10S (BOX OF 40S)'],
            ['code' => 'B1050', 'desc' => 'BLISTER PACK OF 10S (BOX OF 50S)'],
            ['code' => 'B1060', 'desc' => 'BLISTER PACK BY 10S (BOX OF 60S)'],
            ['code' => 'B1080', 'desc' => 'BLISTER PACK OF 10S (BOX OF 80S)'],
            ['code' => 'B10SH', 'desc' => 'BLISTER PACK OF 10S (BOX OF 100S)'],
            ['code' => 'B1412', 'desc' => 'BLISTER PACK BY 14S (BOX OF 112S)'],
            ['code' => 'B1414', 'desc' => 'BLISTER PACK OF 14S (BOX OF 140S)'],
            ['code' => 'B1428', 'desc' => 'BLISTER PACK OF 14S (BOX OF 28S)'],
            ['code' => 'B1429', 'desc' => 'BLISTER PACK OF 14S (BOX OF 294S)'],
            ['code' => 'B1515', 'desc' => 'BLISTER PACK OF 15S (BOX OF 150S)'],
            ['code' => 'B1530', 'desc' => 'BLISTER PACK OF 15S (BOX OF 30S)'],
            ['code' => 'B2040', 'desc' => 'BLISTER PACK OF 20S (BOX OF 40S)'],
            ['code' => 'B2080', 'desc' => 'BLISTER PACK OF 20S (BOX OF 80S)'],
            ['code' => 'B3060', 'desc' => 'BLISTER PACK OF 30S (BOX OF 60S)'],
            ['code' => 'B550S', 'desc' => 'BLISTER PACK BY 5S (BOX OF 100S)'],
            ['code' => 'B8120', 'desc' => 'BLISTER PACK OF 8S (BOX OF 120S)'],
            ['code' => 'BAGXX', 'desc' => 'BAG'],
            ['code' => 'BF100', 'desc' => 'BLISTER FOIL BY 100S'],
            ['code' => 'BF250', 'desc' => 'BLISTER FOIL BY 250S'],
            ['code' => 'BF30X', 'desc' => 'BLISTER FOIL BY 30S'],
            ['code' => 'BF60S', 'desc' => 'BLISTER FOIL BY 60S'],
            ['code' => 'BFOIL', 'desc' => 'BLISTER FOIL'],
            ['code' => 'BFT10', 'desc' => 'BLISTER FOIL BY 10S'],
            ['code' => 'BFTCL', 'desc' => 'BLISTER FOIL BY 10S (BOX OF 50S)'],
            ['code' => 'BFTCX', 'desc' => 'BLISTER FOIL BY 10S (BOX OF 100S)'],
            ['code' => 'BFTLX', 'desc' => 'BLISTER FOIL BY 50S'],
            ['code' => 'BOTTL', 'desc' => 'BOTTLE'],
            ['code' => 'BOX10', 'desc' => 'BLISTER BOX OF 10'],
            ['code' => 'BOX30', 'desc' => 'BLISTER BOX OF 30'],
            ['code' => 'BOX50', 'desc' => 'BLISTER BOX OF 50'],
            ['code' => 'BOXHX', 'desc' => 'BOX OF 100S'],
            ['code' => 'BOXLX', 'desc' => 'BOX OF 50S'],
            ['code' => 'BOXTX', 'desc' => 'BOX OF 10S'],
            ['code' => 'BP100', 'desc' => 'BLISTER PACK X 100'],
            ['code' => 'BP10X', 'desc' => 'BLISTER PACK X 10'],
            ['code' => 'BP110', 'desc' => 'BLISTER PACK BY 10S (BOX OF 110S)'],
            ['code' => 'BP112', 'desc' => 'BLISTER PACK X 112'],
            ['code' => 'BP141', 'desc' => 'BLISTER PACK OF 14S (BOX OF 14S)'],
            ['code' => 'BP144', 'desc' => 'BLISTER PACK BY 14S (BOX OF 140S)'],
            ['code' => 'BP14X', 'desc' => 'BLISTER PACK X 14'],
            ['code' => 'BP150', 'desc' => 'BLISTER PACK X 150'],
            ['code' => 'BP200', 'desc' => 'BLISTER PACK X 200'],
            ['code' => 'BP202', 'desc' => 'BLISTER PACK OF 20S (BOX OF 20S)'],
            ['code' => 'BP205', 'desc' => 'BLISTER PACK OF 20S (BOX OF 5S)'],
            ['code' => 'BP20H', 'desc' => 'BLISTER PACK OF 20S (BOX OF 100S)'],
            ['code' => 'BP20L', 'desc' => 'BLISTER PACK OF 20S (BOX OF 50S)'],
            ['code' => 'BP20X', 'desc' => 'BLISTER PACK X 20'],
            ['code' => 'BP25H', 'desc' => 'BLISTER PACK OF 20S (BOX OF 500S)'],
            ['code' => 'BP294', 'desc' => 'BLISTER PACK X 294'],
            ['code' => 'BP2T2', 'desc' => 'BLISTER PACK OF 20S (BOX OF 200S)'],
            ['code' => 'BP2TH', 'desc' => 'BLISTER PACK OF 20S (BOX OF 1000S)'],
            ['code' => 'BP30X', 'desc' => 'BLISTER PACK X 30'],
            ['code' => 'BP324', 'desc' => 'BLISTER PACK OF 3S (BOX OF 24S)'],
            ['code' => 'BP330', 'desc' => 'BLISTER PACK OF 3S (BOX OF 30S)'],
            ['code' => 'BP3X3', 'desc' => 'BLISTER PACK OF 3S (BOX OF 3S)'],
            ['code' => 'BP3XX', 'desc' => 'BLISTER PACK X 3'],
            ['code' => 'BP412', 'desc' => 'BLISTER PACK OF 4S (BOX OF 12S)'],
            ['code' => 'BP420', 'desc' => 'BLISTER PACK OF 4S (BOX OF 20S)'],
            ['code' => 'BP440', 'desc' => 'BLISTER PACK OF 4S (BOX OF 40S)'],
            ['code' => 'BP460', 'desc' => 'BLISTER PACK OF 4S (BOX OF 60S)'],
            ['code' => 'BP48S', 'desc' => 'BLISTER PACK X 48'],
            ['code' => 'BP4XX', 'desc' => 'BLISTER PACK X 4'],
            ['code' => 'BP50X', 'desc' => 'BLISTER PACK X 50'],
            ['code' => 'BP510', 'desc' => 'BLISTER PACK OF 5S (BOX OF 10S)'],
            ['code' => 'BP515', 'desc' => 'BLISTER PACK BY 5S (BOX OF 15S)'],
            ['code' => 'BP520', 'desc' => 'BLISTER PACK OF 5S X 20 (BOX OF 100S)'],
            ['code' => 'BP530', 'desc' => 'BLISTER PACK BY 5S (BOX OF 30S)'],
            ['code' => 'BP550', 'desc' => 'BLISTER PACK OF 5S (BOX OF 50S)'],
            ['code' => 'BP560', 'desc' => 'BLISTER PACK BY 5S (BOX OF 60S)'],
            ['code' => 'BP5TW', 'desc' => 'BLISTER PACK BY 5S (BOX OF 20S)'],
            ['code' => 'BP5X5', 'desc' => 'BLISTER PACK OF 5S (BOX OF 5S)'],
            ['code' => 'BP5XX', 'desc' => 'BLISTER PACK X 5'],
            ['code' => 'BP60S', 'desc' => 'BLISTER PACK OF 20S (BOX OF 60S)'],
            ['code' => 'BP60X', 'desc' => 'BLISTER PACK X 60'],
            ['code' => 'BP624', 'desc' => 'BLISTER PACK OF 6S (BOX OF 24S)'],
            ['code' => 'BP630', 'desc' => 'BLISTER PACK OF 6S (BOX OF 30S)'],
            ['code' => 'BP648', 'desc' => 'BLISTER PACK OF 6S (BOX OF 48S)'],
            ['code' => 'BP660', 'desc' => 'BLISTER PACK BY 6S (BOX OF 60S)'],
            ['code' => 'BP6SX', 'desc' => 'BLISTER PACK X 6'],
            ['code' => 'BP714', 'desc' => 'BLISTER PACK OF 7S (BOX OF 14S)'],
            ['code' => 'BP724', 'desc' => 'BLISTER PACK OF 7S (BOX OF 24S)'],
            ['code' => 'BP728', 'desc' => 'BLISTER PACK BY 7S (BOX OF 28S)'],
            ['code' => 'BP7SX', 'desc' => 'BLISTER PACK X 7'],
            ['code' => 'BP824', 'desc' => 'BLISTER PACK OF 8S (BOX OF 24S)'],
            ['code' => 'BP832', 'desc' => 'BLISTER PACK BY 8S (BOX OF 32S)'],
            ['code' => 'BP840', 'desc' => 'BLISTER PACK BY 8S (BOX OF 40S)'],
            ['code' => 'BP848', 'desc' => 'BLISTER PACK OF 8S (BOX OF 48S)'],
            ['code' => 'BP860', 'desc' => 'BLISTER PACK OF 8S (BOX OF 60S)'],
            ['code' => 'BP880', 'desc' => 'BLISTER PACK BY 8S (BOX OF 80S)'],
            ['code' => 'BP8SX', 'desc' => 'BLISTER PACK X 8'],
            ['code' => 'BPC10', 'desc' => 'BLISTER PACK OF 100S (BOX OF 10S)'],
            ['code' => 'BPHXH', 'desc' => 'BLISTER PACK OF 100S (BOX OF 100S)'],
            ['code' => 'BPV20', 'desc' => 'BLISTER PACK OF 5S (BOX OF 20S)'],
            ['code' => 'BPX12', 'desc' => 'BLISTER PACK OF 10S (BOX OF 120S)'],
            ['code' => 'BPX20', 'desc' => 'BLISTER PACK OF 10S (BOX OF 20S)'],
            ['code' => 'BPX2H', 'desc' => 'BLISTER PACK BY 10S (BOX OF 200S)'],
            ['code' => 'BPX30', 'desc' => 'BLISTER PACK OF 10S (BOX OF 30S)'],
            ['code' => 'BPX5H', 'desc' => 'BLISTER PACK BY 10S (BOX OF 500S)'],
            ['code' => 'BPX90', 'desc' => 'BLISTER PACK BY 10S (BOX OF 90S)'],
            ['code' => 'BPXXX', 'desc' => 'BLISTER PACK'],
            ['code' => 'BS100', 'desc' => 'BLISTER STRIP X 100'],
            ['code' => 'BS10H', 'desc' => 'BLISTER STRIP BY 10 (BOX OF 100S)'],
            ['code' => 'BS10S', 'desc' => 'BLISTER STRIP BY 10S'],
            ['code' => 'BS2HX', 'desc' => 'BLISTER STRIP 20S (BOX OF 100S)'],
            ['code' => 'BS310', 'desc' => 'CLEAR PVC/ALUMINUM BLISTER STRIP 3 X 10S'],
            ['code' => 'BS50X', 'desc' => 'BLISTER STRIP X 50'],
            ['code' => 'BS520', 'desc' => 'BLISTER STRIP 5 X 20S (BOX OF 100S)'],
            ['code' => 'BS610', 'desc' => 'CLEAR PVC/ALUMINUM BLISTER STRIP 6 X 10S'],
            ['code' => 'BS7XX', 'desc' => 'BLISTER STRIP BY 7'],
            ['code' => 'BST20', 'desc' => 'BLISTER STRIP BY 10 (BOX OF 20S)'],
            ['code' => 'BST50', 'desc' => 'BLISTER STRIP BY 10 (BOX OF 50S)'],
            ['code' => 'BSTTH', 'desc' => 'BLISTER STRIP 10 X 10S (BOX OF 100S)'],
            ['code' => 'BSXXX', 'desc' => 'BLISTER STRIP'],
            ['code' => 'BX150', 'desc' => 'BLISTER PACK OF 10S (BOX OF 150S)'],
            ['code' => 'CANIS', 'desc' => 'CANISTER'],
            ['code' => 'COLOA', 'desc' => 'COLORLESS AMPUL'],
            ['code' => 'COLOG', 'desc' => 'COLORLESS GLASS'],
            ['code' => 'DFPHS', 'desc' => 'DOUBLE FOIL BLISTERS, 100S'],
            ['code' => 'FBSTR', 'desc' => 'FOIL BLISTER STRIP'],
            ['code' => 'FF10X', 'desc' => 'FLEX FOIL BY 10S (BOX OF 150S)'],
            ['code' => 'FF4HX', 'desc' => 'FLEX FOIL BY 4S (BOX OF 100S)'],
            ['code' => 'FFS25', 'desc' => 'FLEX FOIL STRIP 25 X 4S (BOX OF 100S)'],
            ['code' => 'FFSXX', 'desc' => 'FLEX FOIL STRIP'],
            ['code' => 'FFT10', 'desc' => 'FLEX FOIL BY 10S'],
            ['code' => 'FFT50', 'desc' => 'FLEX FOIL BY 10S (BOX OF 50S)'],
            ['code' => 'FP330', 'desc' => 'FOIL PACK BY 3 (BOX OF 30S)'],
            ['code' => 'FP4BC', 'desc' => 'FOIL PACK BY 4 (BOX OF 100S)'],
            ['code' => 'FS100', 'desc' => 'FOIL STRIP BY 100S'],
            ['code' => 'FS101', 'desc' => 'FOIL STRIP BY 10S (BOX OF 10S)'],
            ['code' => 'FS102', 'desc' => 'FOIL STRIP BY 10S (BOX OF 20S)'],
            ['code' => 'FS103', 'desc' => 'FOIL STRIP BY 10S (BOX OF 30S)'],
            ['code' => 'FS105', 'desc' => 'FOIL STRIP BY 10S (BOX OF 50S)'],
            ['code' => 'FS106', 'desc' => 'FOIL STRIP BY 10S (BOX OF 60S)'],
            ['code' => 'FS10L', 'desc' => 'FOIL STRIP 10 X 10S (BOX OF 50S)'],
            ['code' => 'FS10S', 'desc' => 'FOIL STRIP BY 10S (BOX OF 150S)'],
            ['code' => 'FS10T', 'desc' => 'FOIL STRIP 10 X 10S (BOX OF 100S)'],
            ['code' => 'FS10X', 'desc' => 'FOIL STRIP BY 10S (BOX OF 100S)'],
            ['code' => 'FS114', 'desc' => 'FOIL STRIP BY 10S (BOX OF 14S)'],
            ['code' => 'FS14X', 'desc' => 'FOIL STRIP BY 14S'],
            ['code' => 'FS153', 'desc' => 'FOIL STRIP BY 15 (BOX OF 30S)'],
            ['code' => 'FS155', 'desc' => 'FOIL STRIP 10 B81X 5S (BOX OF 50S)'],
            ['code' => 'FS156', 'desc' => 'FOIL STRIP BY 15 (BOX OF 60S)'],
            ['code' => 'FS15X', 'desc' => 'FOIL STRIP BY 15S'],
            ['code' => 'FS250', 'desc' => 'FOIL STRIP BY 10S (BOX OF 250S)'],
            ['code' => 'FS25H', 'desc' => 'FOIL STRIP BY 25S (BOX OF 100S)'],
            ['code' => 'FS28X', 'desc' => 'FOIL STRIP BY 28S'],
            ['code' => 'FS30X', 'desc' => 'FOIL STRIP BY 30S'],
            ['code' => 'FS321', 'desc' => 'FOIL STRIP BY 3 (BOX OF 21S)'],
            ['code' => 'FS3X3', 'desc' => 'FOIL STRIP BY 3 (BOX OF 3S)'],
            ['code' => 'FS412', 'desc' => 'FOIL STRIP BY 4S (BOX OF 12S)'],
            ['code' => 'FS414', 'desc' => 'FOIL STRIP BY 4S (BOX OF 14S)'],
            ['code' => 'FS420', 'desc' => 'FOIL STRIP BY 4S (BOX OF 20S)'],
            ['code' => 'FS421', 'desc' => 'FOIL STRIP BY 4S (BOX OF 21S)'],
            ['code' => 'FS424', 'desc' => 'FOIL STRIP BY 4S (BOX OF 24S)'],
            ['code' => 'FS428', 'desc' => 'FOIL STRIP BY 4S (BOX OF 28S)'],
            ['code' => 'FS430', 'desc' => 'FOIL STRIP BY 4S (BOX OF 30S)'],
            ['code' => 'FS450', 'desc' => 'FOIL STRIP BY 4S (BOX OF 50S)'],
            ['code' => 'FS460', 'desc' => 'FOIL STRIP BY 4S (BOX OF 60S)'],
            ['code' => 'FS480', 'desc' => 'FOIL STRIP BY 4S (BOX OF 80S)'],
            ['code' => 'FS4CX', 'desc' => 'FOIL STRIP BY 4S (BOX OF 100S)'],
            ['code' => 'FS4HX', 'desc' => 'FOIL STRIP BY 4S (BOX OF 100S)'],
            ['code' => 'FS4S4', 'desc' => 'FOIL STRIP BY 4S (BOX OF 40S)'],
            ['code' => 'FS4XX', 'desc' => 'FOLI STRIP BY 4S'],
            ['code' => 'FS50X', 'desc' => 'FOIL STRIP BY 50S'],
            ['code' => 'FS60X', 'desc' => 'FOIL STRIP BY 60S'],
            ['code' => 'FS612', 'desc' => 'FOIL STRIP BY 6S (BOX OF 12S)'],
            ['code' => 'FS630', 'desc' => 'FOIL STRIP BY 6S (BOX OF 30S)'],
            ['code' => 'FS660', 'desc' => 'FOIL STRIP BY 6S (BOX OF 60S)'],
            ['code' => 'FS840', 'desc' => 'FOIL STRIP BY 8S (BOX OF 40S)'],
            ['code' => 'FS880', 'desc' => 'FOIL STRIP BY 8S (BOX OF 80S)'],
            ['code' => 'FS88X', 'desc' => 'FOIL STRIP BY 8S (BOX OF 8S)'],
            ['code' => 'FS90X', 'desc' => 'FOIL STRIP BY 90S'],
            ['code' => 'FSTRI', 'desc' => 'FOIL STRIP'],
            ['code' => 'FSTT1', 'desc' => 'FOIL STRIP BY 21S'],
            ['code' => 'FSTTW', 'desc' => 'FOIL STRIP BY 20S'],
            ['code' => 'FSTTX', 'desc' => 'FOIL STRIP BY 20S (BOX OF 100S)'],
            ['code' => 'FSTXX', 'desc' => 'FOIL STRIP BY 10S'],
            ['code' => 'FVIAL', 'desc' => 'FLINT VIAL'],
            ['code' => 'FX500', 'desc' => 'FOIL STRIP BY 10S (BOX OF 500S)'],
            ['code' => 'GLAMP', 'desc' => 'GLASS AMPUL'],
            ['code' => 'GVIAL', 'desc' => 'GLASS VIAL'],
            ['code' => 'PB100', 'desc' => 'PLASTIC BOTTLE BY 100S'],
            ['code' => 'PLASB', 'desc' => 'PLASTIC BOTTLE'],
            ['code' => 'PR100', 'desc' => 'PROPYLENE BAG X 100 ML'],
            ['code' => 'PVC10', 'desc' => 'PVC BLISTER PACK BY 10S (BOX OF 100S)'],
            ['code' => 'PVC50', 'desc' => 'PVC/AL BLISTER PACK BY 10S (BOX OF 50S)'],
            ['code' => 'PVCAL', 'desc' => 'PVC/ALU BLISTER'],
            ['code' => 'ROTAP', 'desc' => 'ROTAPLAST'],
            ['code' => 'SPT10', 'desc' => 'STRIP PACK BY 10S (BOX OF 100S)'],
            ['code' => 'SPT20', 'desc' => 'STRIP PACK BY 10S (BOX OF 20S)'],
            ['code' => 'SPT30', 'desc' => 'STRIP PACK BY 10S (BOX OF 30S)'],
            ['code' => 'SPT50', 'desc' => 'STRIP PACK BY 10S (BOX OF 50S)'],
            ['code' => 'SPT80', 'desc' => 'STRIP PACK BY 10S (BOX OF 80S)'],
            ['code' => 'VIALX', 'desc' => 'VIAL'],
            ['code' => 'XXXX', 'desc' => 'XXXX'],
            ['code' => 'SAC01', 'desc' => 'SACHET'],
            ['code' => '00000', 'desc' => 'N/A'],
            ['code' => 'TUB01', 'desc' => 'TUBE'],
            ['code' => 'USP02', 'desc' => 'USP'],
            ['code' => 'GB001', 'desc' => 'GLASS BOTTLE'],
            ['code' => 'DRO01', 'desc' => 'DROPS'],
            ['code' => 'JAR01', 'desc' => 'JAR'],
            ['code' => 'PLB01', 'desc' => 'POUCHED LDPE BAG'],
            ['code' => 'DIS01', 'desc' => 'DISPENSER'],
            ['code' => 'BAM01', 'desc' => 'BREATH ACTUATED MDI'],
            ['code' => 'SOA01', 'desc' => 'SOAP'],
            ['code' => 'GC001', 'desc' => 'GLASS CARTRIDGE'],
            ['code' => 'PFS01', 'desc' => 'PRE-FILLED SYRINGE'],
            ['code' => 'DRU01', 'desc' => 'DRUM'],
            ['code' => 'INH01', 'desc' => 'INHALER'],
            ['code' => 'NEB01', 'desc' => 'NEBULE'],
            ['code' => 'MDI01', 'desc' => 'METERED DOSE INHALER'],
            ['code' => 'DS001', 'desc' => 'DISPOSABLE SYRINGE'],
            ['code' => 'DIC01', 'desc' => 'DUPLEX III CONTAINER'],
            ['code' => 'DPB01', 'desc' => 'D5W PRE-MIXED BOTTLE'],
            ['code' => 'CAN01', 'desc' => 'CAN'],
            ['code' => 'AI001', 'desc' => 'AUTO-INJECTOR'],
            ['code' => 'PFS02', 'desc' => 'PRE-FILLED SYRINGE (HAS FREE)'],
            ['code' => 'PFG01', 'desc' => 'PRE-FILLED GLASS SYRINGE'],
            ['code' => 'ELI01', 'desc' => 'ELIXIR'],
            ['code' => 'PSN01', 'desc' => 'PRE-FILLED SYRINGE WITH NEEDLE'],
            ['code' => 'IMP01', 'desc' => 'IMPLANT'],
            ['code' => 'GAL01', 'desc' => 'GALLON'],
            ['code' => 'PFS03', 'desc' => 'PRE-FILLED SYRINGE (SINGLE DOSE)'],
            ['code' => 'MV001', 'desc' => 'MONODOSE VIAL'],
            ['code' => 'GPS01', 'desc' => 'GLASS PRE-FILLED SYRINGE'],
            ['code' => 'VPS01', 'desc' => 'VIAL + PRE-FILLED SYRINGE DILUENT'],
            ['code' => 'SDS01', 'desc' => 'SINGLE DOSE WITH SYRINGE'],
            ['code' => 'VS001', 'desc' => 'VIAL + SYRINGE'],
            ['code' => 'CAR01', 'desc' => 'CARPULE'],
            ['code' => 'PRM01', 'desc' => 'PRE-MIXED'],
            ['code' => 'PLT01', 'desc' => 'PLASTIC TUBE'],
            ['code' => 'VA001', 'desc' => 'VIAL + AMPULE'],
            ['code' => 'CP001', 'desc' => 'COMBO-PACK '],
            ['code' => 'CYC01', 'desc' => 'CYCLE'],
            ['code' => 'LPV01', 'desc' => 'LYOPHILIZED POWDER + VIAL'],
            ['code' => 'LPS01', 'desc' => 'LYOPHILIZED POWDER + SYRINGE'],
            ['code' => 'VPS02', 'desc' => 'VIAL + PRE-FILLED SYRINGE'],
            ['code' => 'POUC1', 'desc' => 'POUCH'],
            ['code' => 'CAR10', 'desc' => 'CARTRIDGE'],
            ['code' => 'CRRT1', 'desc' => 'CRRT'],
        ], ['code']);
    }
}
