<?php

namespace Database\Seeders;

use App\Models\V1\Libraries\LibLengthHeightForAge;
use Illuminate\Database\Seeder;

class LibLengthHeightForAgeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        LibLengthHeightForAge::truncate();
        LibLengthHeightForAge::upsert([
            ['age_month' => '0', 'length_min' => '44.1', 'length_max' => '44.1', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '0', 'length_min' => '44.2', 'length_max' => '46.0', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '0', 'length_min' => '46.1', 'length_max' => '53.7', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '0', 'length_min' => '53.8', 'length_max' => '53.8', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '1', 'length_min' => '48.8', 'length_max' => '48.8', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '1', 'length_min' => '48.9', 'length_max' => '50.7', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '1', 'length_min' => '50.8', 'length_max' => '58.6', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '1', 'length_min' => '58.7', 'length_max' => '58.7', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '2', 'length_min' => '52.3', 'length_max' => '52.3', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '2', 'length_min' => '52.4', 'length_max' => '54.3', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '2', 'length_min' => '54.4', 'length_max' => '62.4', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '2', 'length_min' => '62.5', 'length_max' => '62.5', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '3', 'length_min' => '55.2', 'length_max' => '55.2', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '3', 'length_min' => '55.3', 'length_max' => '57.2', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '3', 'length_min' => '57.3', 'length_max' => '65.5', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '3', 'length_min' => '65.6', 'length_max' => '65.6', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '4', 'length_min' => '57.5', 'length_max' => '57.5', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '4', 'length_min' => '57.6', 'length_max' => '59.6', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '4', 'length_min' => '59.7', 'length_max' => '68.0', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '4', 'length_min' => '68.1', 'length_max' => '68.1', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '5', 'length_min' => '59.5', 'length_max' => '59.5', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '5', 'length_min' => '59.6', 'length_max' => '61.6', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '5', 'length_min' => '61.7', 'length_max' => '70.1', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '5', 'length_min' => '70.2', 'length_max' => '70.2', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '6', 'length_min' => '61.1', 'length_max' => '61.1', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '6', 'length_min' => '61.2', 'length_max' => '63.2', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '6', 'length_min' => '63.3', 'length_max' => '71.9', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '6', 'length_min' => '72.0', 'length_max' => '72.0', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '7', 'length_min' => '62.6', 'length_max' => '62.6', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '7', 'length_min' => '62.7', 'length_max' => '64.7', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '7', 'length_min' => '64.8', 'length_max' => '73.5', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '7', 'length_min' => '73.6', 'length_max' => '73.6', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '8', 'length_min' => '63.9', 'length_max' => '63.9', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '8', 'length_min' => '64.0', 'length_max' => '66.1', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '8', 'length_min' => '66.2', 'length_max' => '75.0', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '8', 'length_min' => '75.1', 'length_max' => '75.1', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '9', 'length_min' => '65.1', 'length_max' => '65.1', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '9', 'length_min' => '65.2', 'length_max' => '67.4', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '9', 'length_min' => '67.5', 'length_max' => '76.5', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '9', 'length_min' => '76.6', 'length_max' => '76.6', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '10', 'length_min' => '66.3', 'length_max' => '66.3', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '10', 'length_min' => '66.4', 'length_max' => '68.6', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '10', 'length_min' => '68.7', 'length_max' => '77.9', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '10', 'length_min' => '78.0', 'length_max' => '78.0', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '11', 'length_min' => '67.5', 'length_max' => '67.5', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '11', 'length_min' => '67.6', 'length_max' => '69.8', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '11', 'length_min' => '69.9', 'length_max' => '79.2', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '11', 'length_min' => '79.3', 'length_max' => '79.3', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '12', 'length_min' => '68.5', 'length_max' => '68.5', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '12', 'length_min' => '68.6', 'length_max' => '70.9', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '12', 'length_min' => '71.0', 'length_max' => '80.5', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '12', 'length_min' => '80.6', 'length_max' => '80.6', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '13', 'length_min' => '69.5', 'length_max' => '69.5', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '13', 'length_min' => '69.6', 'length_max' => '72.0', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '13', 'length_min' => '72.1', 'length_max' => '81.8', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '13', 'length_min' => '81.9', 'length_max' => '81.9', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '14', 'length_min' => '70.5', 'length_max' => '70.5', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '14', 'length_min' => '70.6', 'length_max' => '73.0', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '14', 'length_min' => '73.1', 'length_max' => '83.0', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '14', 'length_min' => '83.1', 'length_max' => '83.1', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '15', 'length_min' => '71.5', 'length_max' => '71.5', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '15', 'length_min' => '71.6', 'length_max' => '74.0', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '15', 'length_min' => '74.1', 'length_max' => '84.2', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '15', 'length_min' => '84.3', 'length_max' => '84.3', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '16', 'length_min' => '72.4', 'length_max' => '72.4', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '16', 'length_min' => '72.5', 'length_max' => '74.9', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '16', 'length_min' => '75.0', 'length_max' => '85.4', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '16', 'length_min' => '85.5', 'length_max' => '85.5', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '17', 'length_min' => '73.2', 'length_max' => '73.2', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '17', 'length_min' => '73.3', 'length_max' => '75.9', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '17', 'length_min' => '76.0', 'length_max' => '86.5', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '17', 'length_min' => '86.6', 'length_max' => '86.6', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '18', 'length_min' => '74.1', 'length_max' => '74.1', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '18', 'length_min' => '74.2', 'length_max' => '76.8', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '18', 'length_min' => '76.9', 'length_max' => '87.7', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '18', 'length_min' => '87.8', 'length_max' => '87.8', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '19', 'length_min' => '74.9', 'length_max' => '74.9', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '19', 'length_min' => '75.0', 'length_max' => '77.6', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '19', 'length_min' => '77.7', 'length_max' => '88.8', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '19', 'length_min' => '88.9', 'length_max' => '88.9', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '20', 'length_min' => '75.7', 'length_max' => '75.7', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '20', 'length_min' => '75.8', 'length_max' => '78.5', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '20', 'length_min' => '78.6', 'length_max' => '89.8', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '20', 'length_min' => '89.9', 'length_max' => '89.9', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '21', 'length_min' => '76.4', 'length_max' => '76.4', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '21', 'length_min' => '76.5', 'length_max' => '79.3', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '21', 'length_min' => '79.4', 'length_max' => '90.9', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '21', 'length_min' => '91.0', 'length_max' => '91.0', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '22', 'length_min' => '77.1', 'length_max' => '77.1', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '22', 'length_min' => '77.2', 'length_max' => '80.1', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '22', 'length_min' => '80.2', 'length_max' => '91.9', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '22', 'length_min' => '92.0', 'length_max' => '92.0', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '23', 'length_min' => '77.9', 'length_max' => '77.9', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '23', 'length_min' => '78.0', 'length_max' => '80.9', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '23', 'length_min' => '81.0', 'length_max' => '92.9', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '23', 'length_min' => '93.0', 'length_max' => '93.0', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '24', 'length_min' => '77.9', 'length_max' => '77.9', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '24', 'length_min' => '78.0', 'length_max' => '80.9', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '24', 'length_min' => '81.0', 'length_max' => '93.2', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '24', 'length_min' => '93.3', 'length_max' => '93.3', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '25', 'length_min' => '78.5', 'length_max' => '78.5', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '25', 'length_min' => '78.6', 'length_max' => '81.6', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '25', 'length_min' => '81.7', 'length_max' => '94.2', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '25', 'length_min' => '94.3', 'length_max' => '94.3', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '26', 'length_min' => '79.2', 'length_max' => '79.2', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '26', 'length_min' => '79.3', 'length_max' => '82.4', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '26', 'length_min' => '82.5', 'length_max' => '95.2', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '26', 'length_min' => '95.3', 'length_max' => '95.3', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '27', 'length_min' => '79.8', 'length_max' => '79.8', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '27', 'length_min' => '79.9', 'length_max' => '83.0', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '27', 'length_min' => '83.1', 'length_max' => '96.1', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '27', 'length_min' => '96.2', 'length_max' => '96.2', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '28', 'length_min' => '80.4', 'length_max' => '80.4', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '28', 'length_min' => '80.5', 'length_max' => '83.7', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '28', 'length_min' => '83.8', 'length_max' => '97.0', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '28', 'length_min' => '97.1', 'length_max' => '97.1', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '29', 'length_min' => '81.0', 'length_max' => '81.0', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '29', 'length_min' => '81.1', 'length_max' => '84.4', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '29', 'length_min' => '84.5', 'length_max' => '97.9', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '29', 'length_min' => '98.0', 'length_max' => '98.0', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '30', 'length_min' => '81.6', 'length_max' => '81.6', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '30', 'length_min' => '81.7', 'length_max' => '85.0', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '30', 'length_min' => '85.1', 'length_max' => '98.7', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '30', 'length_min' => '98.8', 'length_max' => '98.8', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '31', 'length_min' => '82.2', 'length_max' => '82.2', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '31', 'length_min' => '82.3', 'length_max' => '85.6', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '31', 'length_min' => '85.7', 'length_max' => '99.6', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '31', 'length_min' => '99.7', 'length_max' => '99.7', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '32', 'length_min' => '82.7', 'length_max' => '82.7', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '32', 'length_min' => '82.8', 'length_max' => '86.3', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '32', 'length_min' => '86.4', 'length_max' => '100.4', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '32', 'length_min' => '100.5', 'length_max' => '100.5', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '33', 'length_min' => '83.3', 'length_max' => '83.3', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '33', 'length_min' => '83.4', 'length_max' => '86.8', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '33', 'length_min' => '86.9', 'length_max' => '101.2', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '33', 'length_min' => '101.3', 'length_max' => '101.3', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '34', 'length_min' => '83.8', 'length_max' => '83.8', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '34', 'length_min' => '83.9', 'length_max' => '87.4', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '34', 'length_min' => '87.5', 'length_max' => '102.0', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '34', 'length_min' => '102.1', 'length_max' => '102.1', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '35', 'length_min' => '84.3', 'length_max' => '84.3', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '35', 'length_min' => '84.4', 'length_max' => '88.0', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '35', 'length_min' => '88.1', 'length_max' => '102.7', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '35', 'length_min' => '102.8', 'length_max' => '102.8', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '36', 'length_min' => '84.9', 'length_max' => '084.9', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '36', 'length_min' => '85.0', 'length_max' => '88.6', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '36', 'length_min' => '88.7', 'length_max' => '103.5', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '36', 'length_min' => '103.6', 'length_max' => '103.6', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '37', 'length_min' => '85.4', 'length_max' => '85.4', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '37', 'length_min' => '85.5', 'length_max' => '89.1', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '37', 'length_min' => '89.2', 'length_max' => '104.2', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '37', 'length_min' => '104.3', 'length_max' => '104.3', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '38', 'length_min' => '85.9', 'length_max' => '85.9', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '38', 'length_min' => '86.0', 'length_max' => '89.7', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '38', 'length_min' => '89.8', 'length_max' => '105.0', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '38', 'length_min' => '105.1', 'length_max' => '105.1', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '39', 'length_min' => '86.4', 'length_max' => '86.4', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '39', 'length_min' => '86.5', 'length_max' => '90.2', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '39', 'length_min' => '90.3', 'length_max' => '105.7', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '39', 'length_min' => '105.8', 'length_max' => '105.8', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '40', 'length_min' => '86.9', 'length_max' => '86.9', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '40', 'length_min' => '87.0', 'length_max' => '90.8', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '40', 'length_min' => '90.9', 'length_max' => '106.4', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '40', 'length_min' => '106.5', 'length_max' => '106.5', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '41', 'length_min' => '87.4', 'length_max' => '87.4', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '41', 'length_min' => '87.5', 'length_max' => '91.3', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '41', 'length_min' => '91.4', 'length_max' => '107.1', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '41', 'length_min' => '107.2', 'length_max' => '107.2', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '42', 'length_min' => '87.9', 'length_max' => '87.9', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '42', 'length_min' => '88.0', 'length_max' => '91.8', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '42', 'length_min' => '91.9', 'length_max' => '107.8', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '42', 'length_min' => '107.9', 'length_max' => '107.9', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '43', 'length_min' => '88.3', 'length_max' => '88.3', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '43', 'length_min' => '88.4', 'length_max' => '92.3', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '43', 'length_min' => '92.4', 'length_max' => '108.5', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '43', 'length_min' => '108.6', 'length_max' => '108.6', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '44', 'length_min' => '88.8', 'length_max' => '88.8', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '44', 'length_min' => '88.9', 'length_max' => '92.9', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '44', 'length_min' => '93.0', 'length_max' => '109.1', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '44', 'length_min' => '109.2', 'length_max' => '109.2', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '45', 'length_min' => '89.3', 'length_max' => '89.3', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '45', 'length_min' => '89.4', 'length_max' => '93.4', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '45', 'length_min' => '93.5', 'length_max' => '109.8', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '45', 'length_min' => '109.9', 'length_max' => '109.9', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '46', 'length_min' => '89.7', 'length_max' => '89.7', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '46', 'length_min' => '89.8', 'length_max' => '93.9', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '46', 'length_min' => '94.0', 'length_max' => '110.4', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '46', 'length_min' => '110.5', 'length_max' => '110.5', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '47', 'length_min' => '90.2', 'length_max' => '90.2', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '47', 'length_min' => '90.3', 'length_max' => '94.3', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '47', 'length_min' => '94.4', 'length_max' => '111.1', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '47', 'length_min' => '111.2', 'length_max' => '111.2', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '48', 'length_min' => '90.6', 'length_max' => '90.6', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '48', 'length_min' => '90.7', 'length_max' => '94.8', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '48', 'length_min' => '94.9', 'length_max' => '111.7', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '48', 'length_min' => '111.8', 'length_max' => '111.8', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '49', 'length_min' => '91.1', 'length_max' => '91.1', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '49', 'length_min' => '91.2', 'length_max' => '95.3', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '49', 'length_min' => '95.4', 'length_max' => '112.4', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '49', 'length_min' => '112.5', 'length_max' => '112.5', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '50', 'length_min' => '91.5', 'length_max' => '91.5', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '50', 'length_min' => '91.6', 'length_max' => '95.8', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '50', 'length_min' => '95.9', 'length_max' => '113.0', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '50', 'length_min' => '113.1', 'length_max' => '113.1', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '51', 'length_min' => '92.0', 'length_max' => '92.0', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '51', 'length_min' => '92.1', 'length_max' => '96.3', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '51', 'length_min' => '96.4', 'length_max' => '113.6', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '51', 'length_min' => '113.7', 'length_max' => '113.7', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '52', 'length_min' => '92.4', 'length_max' => '92.4', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '52', 'length_min' => '92.5', 'length_max' => '96.8', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '52', 'length_min' => '96.9', 'length_max' => '114.2', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '52', 'length_min' => '114.3', 'length_max' => '114.3', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '53', 'length_min' => '92.9', 'length_max' => '92.9', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '53', 'length_min' => '93.0', 'length_max' => '97.3', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '53', 'length_min' => '97.4', 'length_max' => '114.9', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '53', 'length_min' => '115.0', 'length_max' => '115.0', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '54', 'length_min' => '93.3', 'length_max' => '93.3', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '54', 'length_min' => '93.4', 'length_max' => '97.7', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '54', 'length_min' => '97.8', 'length_max' => '115.5', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '54', 'length_min' => '115.6', 'length_max' => '115.6', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '55', 'length_min' => '93.8', 'length_max' => '93.8', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '55', 'length_min' => '93.9', 'length_max' => '98.2', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '55', 'length_min' => '98.3', 'length_max' => '116.1', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '55', 'length_min' => '116.2', 'length_max' => '116.2', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '56', 'length_min' => '94.2', 'length_max' => '94.2', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '56', 'length_min' => '94.3', 'length_max' => '98.7', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '56', 'length_min' => '98.8', 'length_max' => '116.7', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '56', 'length_min' => '116.8', 'length_max' => '116.8', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '57', 'length_min' => '94.6', 'length_max' => '94.6', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '57', 'length_min' => '94.7', 'length_max' => '99.2', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '57', 'length_min' => '99.3', 'length_max' => '117.4', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '57', 'length_min' => '117.5', 'length_max' => '117.5', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '58', 'length_min' => '95.1', 'length_max' => '95.1', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '58', 'length_min' => '95.2', 'length_max' => '99.6', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '58', 'length_min' => '99.7', 'length_max' => '118.0', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '58', 'length_min' => '118.1', 'length_max' => '118.1', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '59', 'length_min' => '95.5', 'length_max' => '95.5', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '59', 'length_min' => '95.6', 'length_max' => '100.1', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '59', 'length_min' => '100.2', 'length_max' => '118.6', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '59', 'length_min' => '118.7', 'length_max' => '118.7', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '60', 'length_min' => '96.0', 'length_max' => '96.0', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '60', 'length_min' => '96.1', 'length_max' => '100.6', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '60', 'length_min' => '100.7', 'length_max' => '119.2', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '60', 'length_min' => '119.3', 'length_max' => '119.3', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '61', 'length_min' => '96.4', 'length_max' => '96.4', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '61', 'length_min' => '96.5', 'length_max' => '101.0', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '61', 'length_min' => '101.1', 'length_max' => '119.4', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '61', 'length_min' => '119.5', 'length_max' => '119.5', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '62', 'length_min' => '96.8', 'length_max' => '96.8', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '62', 'length_min' => '96.9', 'length_max' => '101.5', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '62', 'length_min' => '101.6', 'length_max' => '120.0', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '62', 'length_min' => '120.1', 'length_max' => '120.1', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '63', 'length_min' => '97.3', 'length_max' => '97.3', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '63', 'length_min' => '97.4', 'length_max' => '101.9', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '63', 'length_min' => '102.0', 'length_max' => '120.6', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '63', 'length_min' => '120.7', 'length_max' => '120.7', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '64', 'length_min' => '97.7', 'length_max' => '97.7', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '64', 'length_min' => '97.8', 'length_max' => '102.4', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '64', 'length_min' => '102.5', 'length_max' => '121.2', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '64', 'length_min' => '121.3', 'length_max' => '121.3', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '65', 'length_min' => '98.1', 'length_max' => '98.1', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '65', 'length_min' => '98.2', 'length_max' => '102.9', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '65', 'length_min' => '103.0', 'length_max' => '121.8', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '65', 'length_min' => '121.9', 'length_max' => '121.9', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '66', 'length_min' => '98.6', 'length_max' => '98.6', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '66', 'length_min' => '98.7', 'length_max' => '103.3', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '66', 'length_min' => '103.4', 'length_max' => '122.4', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '66', 'length_min' => '122.5', 'length_max' => '122.5', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '67', 'length_min' => '99.0', 'length_max' => '99.0', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '67', 'length_min' => '99.1', 'length_max' => '103.8', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '67', 'length_min' => '103.9', 'length_max' => '123.0', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '67', 'length_min' => '123.1', 'length_max' => '123.1', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '68', 'length_min' => '99.4', 'length_max' => '99.4', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '68', 'length_min' => '99.5', 'length_max' => '104.2', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '68', 'length_min' => '104.3', 'length_max' => '123.6', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '68', 'length_min' => '123.7', 'length_max' => '123.7', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '69', 'length_min' => '99.8', 'length_max' => '99.8', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '69', 'length_min' => '99.9', 'length_max' => '104.7', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '69', 'length_min' => '104.8', 'length_max' => '124.1', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '69', 'length_min' => '124.2', 'length_max' => '124.2', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '70', 'length_min' => '100.3', 'length_max' => '100.3', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '70', 'length_min' => '100.4', 'length_max' => '105.1', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '70', 'length_min' => '105.2', 'length_max' => '124.7', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '70', 'length_min' => '124.8', 'length_max' => '124.8', 'gender' => 'M', 'lt_class' => 'Tall'],
            ['age_month' => '71', 'length_min' => '100.7', 'length_max' => '100.7', 'gender' => 'M', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '71', 'length_min' => '100.8', 'length_max' => '105.6', 'gender' => 'M', 'lt_class' => 'Stunted'],
            ['age_month' => '71', 'length_min' => '105.7', 'length_max' => '125.2', 'gender' => 'M', 'lt_class' => 'Normal'],
            ['age_month' => '71', 'length_min' => '125.3', 'length_max' => '125.3', 'gender' => 'M', 'lt_class' => 'Tall'],
            // Girls
            ['age_month' => '0', 'length_min' => '43.5', 'length_max' => '43.5', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '0', 'length_min' => '43.6', 'length_max' => '45.3', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '0', 'length_min' => '45.4', 'length_max' => '52.9', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '0', 'length_min' => '53.0', 'length_max' => '53.0', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '1', 'length_min' => '47.7', 'length_max' => '47.7', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '1', 'length_min' => '47.8', 'length_max' => '49.7', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '1', 'length_min' => '49.8', 'length_max' => '57.6', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '1', 'length_min' => '57.7', 'length_max' => '57.7', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '2', 'length_min' => '50.9', 'length_max' => '50.9', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '2', 'length_min' => '51.0', 'length_max' => '52.9', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '2', 'length_min' => '53.0', 'length_max' => '61.1', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '2', 'length_min' => '61.2', 'length_max' => '61.2', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '3', 'length_min' => '53.4', 'length_max' => '53.4', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '3', 'length_min' => '53.5', 'length_max' => '55.5', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '3', 'length_min' => '55.6', 'length_max' => '64.0', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '3', 'length_min' => '64.1', 'length_max' => '64.1', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '4', 'length_min' => '55.5', 'length_max' => '55.5', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '4', 'length_min' => '55.6', 'length_max' => '57.7', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '4', 'length_min' => '57.8', 'length_max' => '66.4', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '4', 'length_min' => '66.5', 'length_max' => '66.5', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '5', 'length_min' => '57.3', 'length_max' => '57.3', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '5', 'length_min' => '57.4', 'length_max' => '59.5', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '5', 'length_min' => '59.6', 'length_max' => '68.5', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '5', 'length_min' => '68.6', 'length_max' => '68.6', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '6', 'length_min' => '58.8', 'length_max' => '58.8', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '6', 'length_min' => '58.9', 'length_max' => '61.1', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '6', 'length_min' => '61.2', 'length_max' => '70.3', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '6', 'length_min' => '70.4', 'length_max' => '70.4', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '7', 'length_min' => '60.2', 'length_max' => '60.2', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '7', 'length_min' => '60.3', 'length_max' => '62.6', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '7', 'length_min' => '62.7', 'length_max' => '71.9', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '7', 'length_min' => '72.0', 'length_max' => '72.0', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '8', 'length_min' => '61.6', 'length_max' => '61.6', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '8', 'length_min' => '61.7', 'length_max' => '63.9', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '8', 'length_min' => '64.0', 'length_max' => '73.5', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '8', 'length_min' => '73.6', 'length_max' => '73.6', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '9', 'length_min' => '62.8', 'length_max' => '62.8', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '9', 'length_min' => '62.9', 'length_max' => '65.2', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '9', 'length_min' => '65.3', 'length_max' => '75.0', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '9', 'length_min' => '75.1', 'length_max' => '75.1', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '10', 'length_min' => '64.0', 'length_max' => '64.0', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '10', 'length_min' => '64.1', 'length_max' => '66.4', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '10', 'length_min' => '66.5', 'length_max' => '76.4', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '10', 'length_min' => '76.5', 'length_max' => '76.5', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '11', 'length_min' => '65.1', 'length_max' => '65.1', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '11', 'length_min' => '65.2', 'length_max' => '67.6', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '11', 'length_min' => '67.7', 'length_max' => '77.8', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '11', 'length_min' => '77.9', 'length_max' => '77.9', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '12', 'length_min' => '66.2', 'length_max' => '66.2', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '12', 'length_min' => '66.3', 'length_max' => '68.8', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '12', 'length_min' => '68.9', 'length_max' => '79.2', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '12', 'length_min' => '79.3', 'length_max' => '79.3', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '13', 'length_min' => '67.2', 'length_max' => '67.2', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '13', 'length_min' => '67.3', 'length_max' => '69.9', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '13', 'length_min' => '70.0', 'length_max' => '80.5', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '13', 'length_min' => '80.6', 'length_max' => '80.6', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '14', 'length_min' => '68.2', 'length_max' => '68.2', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '14', 'length_min' => '68.3', 'length_max' => '70.9', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '14', 'length_min' => '71.0', 'length_max' => '81.7', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '14', 'length_min' => '81.8', 'length_max' => '81.8', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '15', 'length_min' => '69.2', 'length_max' => '69.2', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '15', 'length_min' => '69.3', 'length_max' => '71.9', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '15', 'length_min' => '72.0', 'length_max' => '83.0', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '15', 'length_min' => '83.1', 'length_max' => '83.1', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '16', 'length_min' => '70.1', 'length_max' => '70.1', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '16', 'length_min' => '70.2', 'length_max' => '72.9', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '16', 'length_min' => '73.0', 'length_max' => '84.2', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '16', 'length_min' => '84.3', 'length_max' => '84.3', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '17', 'length_min' => '71.0', 'length_max' => '71.0', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '17', 'length_min' => '71.1', 'length_max' => '73.9', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '17', 'length_min' => '74.0', 'length_max' => '85.4', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '17', 'length_min' => '85.5', 'length_max' => '85.5', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '18', 'length_min' => '71.9', 'length_max' => '71.9', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '18', 'length_min' => '72.0', 'length_max' => '74.8', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '18', 'length_min' => '74.9', 'length_max' => '86.5', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '18', 'length_min' => '86.6', 'length_max' => '86.6', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '19', 'length_min' => '72.7', 'length_max' => '72.7', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '19', 'length_min' => '72.8', 'length_max' => '75.7', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '19', 'length_min' => '75.8', 'length_max' => '87.6', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '19', 'length_min' => '87.7', 'length_max' => '87.7', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '20', 'length_min' => '73.6', 'length_max' => '73.6', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '20', 'length_min' => '73.7', 'length_max' => '76.6', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '20', 'length_min' => '76.7', 'length_max' => '88.7', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '20', 'length_min' => '88.8', 'length_max' => '88.8', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '21', 'length_min' => '74.4', 'length_max' => '74.4', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '21', 'length_min' => '74.5', 'length_max' => '77.4', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '21', 'length_min' => '77.5', 'length_max' => '89.8', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '21', 'length_min' => '89.9', 'length_max' => '89.9', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '22', 'length_min' => '75.1', 'length_max' => '75.1', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '22', 'length_min' => '75.2', 'length_max' => '78.3', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '22', 'length_min' => '78.4', 'length_max' => '90.8', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '22', 'length_min' => '90.9', 'length_max' => '90.9', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '23', 'length_min' => '75.9', 'length_max' => '75.9', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '23', 'length_min' => '76.0', 'length_max' => '79.1', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '23', 'length_min' => '79.2', 'length_max' => '91.9', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '23', 'length_min' => '92.0', 'length_max' => '92.0', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '24', 'length_min' => '75.9', 'length_max' => '75.9', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '24', 'length_min' => '76.0', 'length_max' => '79.2', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '24', 'length_min' => '79.3', 'length_max' => '92.2', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '24', 'length_min' => '92.3', 'length_max' => '92.3', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '25', 'length_min' => '76.7', 'length_max' => '76.7', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '25', 'length_min' => '76.8', 'length_max' => '79.9', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '25', 'length_min' => '80.0', 'length_max' => '93.1', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '25', 'length_min' => '93.2', 'length_max' => '93.2', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '26', 'length_min' => '77.4', 'length_max' => '77.4', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '26', 'length_min' => '77.5', 'length_max' => '80.7', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '26', 'length_min' => '80.8', 'length_max' => '94.1', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '26', 'length_min' => '94.2', 'length_max' => '94.2', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '27', 'length_min' => '78.0', 'length_max' => '78.0', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '27', 'length_min' => '78.1', 'length_max' => '81.4', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '27', 'length_min' => '81.5', 'length_max' => '95.0', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '27', 'length_min' => '95.1', 'length_max' => '95.1', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '28', 'length_min' => '78.7', 'length_max' => '78.7', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '28', 'length_min' => '78.8', 'length_max' => '82.1', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '28', 'length_min' => '82.2', 'length_max' => '96.0', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '28', 'length_min' => '96.1', 'length_max' => '96.1', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '29', 'length_min' => '79.4', 'length_max' => '79.4', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '29', 'length_min' => '79.5', 'length_max' => '82.8', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '29', 'length_min' => '82.9', 'length_max' => '96.9', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '29', 'length_min' => '97.0', 'length_max' => '97.0', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '30', 'length_min' => '80.0', 'length_max' => '80.0', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '30', 'length_min' => '80.1', 'length_max' => '83.5', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '30', 'length_min' => '83.6', 'length_max' => '97.7', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '30', 'length_min' => '97.8', 'length_max' => '97.8', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '31', 'length_min' => '80.6', 'length_max' => '80.6', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '31', 'length_min' => '80.7', 'length_max' => '84.2', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '31', 'length_min' => '84.3', 'length_max' => '98.6', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '31', 'length_min' => '98.7', 'length_max' => '98.7', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '32', 'length_min' => '81.2', 'length_max' => '81.2', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '32', 'length_min' => '81.3', 'length_max' => '84.8', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '32', 'length_min' => '84.9', 'length_max' => '99.4', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '32', 'length_min' => '99.5', 'length_max' => '99.5', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '33', 'length_min' => '81.8', 'length_max' => '81.8', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '33', 'length_min' => '81.9', 'length_max' => '85.5', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '33', 'length_min' => '85.6', 'length_max' => '100.3', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '33', 'length_min' => '100.4', 'length_max' => '100.4', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '34', 'length_min' => '82.4', 'length_max' => '82.4', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '34', 'length_min' => '82.5', 'length_max' => '86.1', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '34', 'length_min' => '86.2', 'length_max' => '101.1', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '34', 'length_min' => '101.2', 'length_max' => '101.2', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '35', 'length_min' => '83.0', 'length_max' => '83.0', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '35', 'length_min' => '83.1', 'length_max' => '86.7', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '35', 'length_min' => '86.8', 'length_max' => '101.9', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '35', 'length_min' => '102.0', 'length_max' => '102.0', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '36', 'length_min' => '83.5', 'length_max' => '83.5', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '36', 'length_min' => '83.6', 'length_max' => '87.3', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '36', 'length_min' => '87.4', 'length_max' => '102.7', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '36', 'length_min' => '102.8', 'length_max' => '102.8', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '37', 'length_min' => '84.1', 'length_max' => '84.1', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '37', 'length_min' => '84.2', 'length_max' => '87.9', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '37', 'length_min' => '88.0', 'length_max' => '103.4', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '37', 'length_min' => '103.5', 'length_max' => '103.5', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '38', 'length_min' => '84.6', 'length_max' => '84.6', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '38', 'length_min' => '84.7', 'length_max' => '88.5', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '38', 'length_min' => '88.6', 'length_max' => '104.2', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '38', 'length_min' => '104.3', 'length_max' => '104.3', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '39', 'length_min' => '85.2', 'length_max' => '89.1', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '39', 'length_min' => '85.3', 'length_max' => '85.3', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '39', 'length_min' => '89.2', 'length_max' => '105.0', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '39', 'length_min' => '105.1', 'length_max' => '105.1', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '40', 'length_min' => '85.7', 'length_max' => '85.7', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '40', 'length_min' => '85.8', 'length_max' => '89.7', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '40', 'length_min' => '89.8', 'length_max' => '105.7', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '40', 'length_min' => '105.8', 'length_max' => '105.8', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '41', 'length_min' => '86.2', 'length_max' => '86.2', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '41', 'length_min' => '86.3', 'length_max' => '90.3', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '41', 'length_min' => '90.4', 'length_max' => '106.4', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '41', 'length_min' => '106.5', 'length_max' => '106.5', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '42', 'length_min' => '86.7', 'length_max' => '86.7', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '42', 'length_min' => '86.8', 'length_max' => '90.8', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '42', 'length_min' => '90.9', 'length_max' => '107.2', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '42', 'length_min' => '107.3', 'length_max' => '107.3', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '43', 'length_min' => '87.3', 'length_max' => '87.3', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '43', 'length_min' => '87.4', 'length_max' => '91.4', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '43', 'length_min' => '91.5', 'length_max' => '107.9', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '43', 'length_min' => '108.0', 'length_max' => '108.0', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '44', 'length_min' => '87.8', 'length_max' => '87.8', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '44', 'length_min' => '87.9', 'length_max' => '91.9', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '44', 'length_min' => '92.0', 'length_max' => '108.6', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '44', 'length_min' => '108.7', 'length_max' => '108.7', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '45', 'length_min' => '88.3', 'length_max' => '88.3', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '45', 'length_min' => '88.4', 'length_max' => '92.4', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '45', 'length_min' => '92.5', 'length_max' => '109.3', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '45', 'length_min' => '109.4', 'length_max' => '109.4', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '46', 'length_min' => '88.8', 'length_max' => '88.8', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '46', 'length_min' => '88.9', 'length_max' => '93.0', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '46', 'length_min' => '93.1', 'length_max' => '110.0', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '46', 'length_min' => '110.1', 'length_max' => '110.1', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '47', 'length_min' => '89.2', 'length_max' => '89.2', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '47', 'length_min' => '89.3', 'length_max' => '93.5', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '47', 'length_min' => '93.6', 'length_max' => '110.7', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '47', 'length_min' => '110.8', 'length_max' => '110.8', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '48', 'length_min' => '89.7', 'length_max' => '89.7', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '48', 'length_min' => '89.8', 'length_max' => '94.0', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '48', 'length_min' => '94.1', 'length_max' => '111.3', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '48', 'length_min' => '111.4', 'length_max' => '111.4', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '49', 'length_min' => '90.2', 'length_max' => '90.2', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '49', 'length_min' => '90.3', 'length_max' => '94.5', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '49', 'length_min' => '94.6', 'length_max' => '112.0', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '49', 'length_min' => '112.1', 'length_max' => '112.1', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '50', 'length_min' => '90.6', 'length_max' => '90.6', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '50', 'length_min' => '90.7', 'length_max' => '95.0', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '50', 'length_min' => '95.1', 'length_max' => '112.7', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '50', 'length_min' => '112.8', 'length_max' => '112.8', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '51', 'length_min' => '91.1', 'length_max' => '91.1', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '51', 'length_min' => '91.2', 'length_max' => '95.5', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '51', 'length_min' => '95.6', 'length_max' => '113.3', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '51', 'length_min' => '113.4', 'length_max' => '113.4', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '52', 'length_min' => '91.6', 'length_max' => '91.6', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '52', 'length_min' => '91.7', 'length_max' => '96.0', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '52', 'length_min' => '96.1', 'length_max' => '114.0', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '52', 'length_min' => '114.1', 'length_max' => '114.1', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '53', 'length_min' => '92.0', 'length_max' => '92.0', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '53', 'length_min' => '92.1', 'length_max' => '96.5', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '53', 'length_min' => '96.6', 'length_max' => '114.6', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '53', 'length_min' => '114.7', 'length_max' => '114.7', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '54', 'length_min' => '92.5', 'length_max' => '92.5', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '54', 'length_min' => '92.6', 'length_max' => '97.0', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '54', 'length_min' => '97.1', 'length_max' => '115.2', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '54', 'length_min' => '115.3', 'length_max' => '115.3', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '55', 'length_min' => '92.9', 'length_max' => '92.9', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '55', 'length_min' => '93.0', 'length_max' => '97.5', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '55', 'length_min' => '97.6', 'length_max' => '115.9', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '55', 'length_min' => '116.0', 'length_max' => '116.0', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '56', 'length_min' => '93.3', 'length_max' => '93.3', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '56', 'length_min' => '93.4', 'length_max' => '98.0', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '56', 'length_min' => '98.1', 'length_max' => '116.5', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '56', 'length_min' => '116.6', 'length_max' => '116.6', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '57', 'length_min' => '93.8', 'length_max' => '93.8', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '57', 'length_min' => '93.9', 'length_max' => '98.4', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '57', 'length_min' => '98.5', 'length_max' => '117.1', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '57', 'length_min' => '117.2', 'length_max' => '117.2', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '58', 'length_min' => '94.2', 'length_max' => '94.2', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '58', 'length_min' => '94.3', 'length_max' => '98.9', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '58', 'length_min' => '99.0', 'length_max' => '117.7', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '58', 'length_min' => '117.8', 'length_max' => '117.8', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '59', 'length_min' => '94.6', 'length_max' => '94.6', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '59', 'length_min' => '94.7', 'length_max' => '99.4', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '59', 'length_min' => '99.5', 'length_max' => '118.3', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '59', 'length_min' => '118.4', 'length_max' => '118.4', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '60', 'length_min' => '95.1', 'length_max' => '95.1', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '60', 'length_min' => '95.2', 'length_max' => '99.8', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '60', 'length_min' => '99.9', 'length_max' => '118.9', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '60', 'length_min' => '119.0', 'length_max' => '119.0', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '61', 'length_min' => '95.2', 'length_max' => '95.2', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '61', 'length_min' => '95.3', 'length_max' => '100.0', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '61', 'length_min' => '100.1', 'length_max' => '119.1', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '61', 'length_min' => '119.2', 'length_max' => '119.2', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '62', 'length_min' => '95.6', 'length_max' => '95.6', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '62', 'length_min' => '95.7', 'length_max' => '100.4', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '62', 'length_min' => '100.5', 'length_max' => '119.7', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '62', 'length_min' => '119.8', 'length_max' => '119.8', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '63', 'length_min' => '96.0', 'length_max' => '96.0', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '63', 'length_min' => '96.1', 'length_max' => '100.9', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '63', 'length_min' => '101.0', 'length_max' => '120.3', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '63', 'length_min' => '120.4', 'length_max' => '120.4', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '64', 'length_min' => '96.4', 'length_max' => '96.4', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '64', 'length_min' => '96.5', 'length_max' => '101.3', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '64', 'length_min' => '101.4', 'length_max' => '120.9', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '64', 'length_min' => '121.0', 'length_max' => '121.0', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '65', 'length_min' => '96.9', 'length_max' => '96.9', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '65', 'length_min' => '97.0', 'length_max' => '101.8', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '65', 'length_min' => '101.9', 'length_max' => '121.5', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '65', 'length_min' => '121.6', 'length_max' => '121.6', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '66', 'length_min' => '97.3', 'length_max' => '97.3', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '66', 'length_min' => '97.4', 'length_max' => '102.2', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '66', 'length_min' => '102.3', 'length_max' => '122.0', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '66', 'length_min' => '122.1', 'length_max' => '122.1', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '67', 'length_min' => '97.7', 'length_max' => '97.7', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '67', 'length_min' => '97.8', 'length_max' => '102.6', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '67', 'length_min' => '102.7', 'length_max' => '122.6', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '67', 'length_min' => '122.7', 'length_max' => '122.7', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '68', 'length_min' => '98.1', 'length_max' => '98.1', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '68', 'length_min' => '98.2', 'length_max' => '103.1', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '68', 'length_min' => '103.2', 'length_max' => '123.2', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '68', 'length_min' => '123.3', 'length_max' => '123.3', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '69', 'length_min' => '98.5', 'length_max' => '98.5', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '69', 'length_min' => '98.6', 'length_max' => '103.5', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '69', 'length_min' => '103.6', 'length_max' => '123.7', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '69', 'length_min' => '123.8', 'length_max' => '123.8', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '70', 'length_min' => '98.9', 'length_max' => '98.9', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '70', 'length_min' => '99.0', 'length_max' => '103.9', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '70', 'length_min' => '104.0', 'length_max' => '124.3', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '70', 'length_min' => '124.4', 'length_max' => '124.4', 'gender' => 'F', 'lt_class' => 'Tall'],
            ['age_month' => '71', 'length_min' => '99.3', 'length_max' => '99.3', 'gender' => 'F', 'lt_class' => 'Severely Stunted'],
            ['age_month' => '71', 'length_min' => '99.4', 'length_max' => '104.4', 'gender' => 'F', 'lt_class' => 'Stunted'],
            ['age_month' => '71', 'length_min' => '104.5', 'length_max' => '124.8', 'gender' => 'F', 'lt_class' => 'Normal'],
            ['age_month' => '71', 'length_min' => '124.9', 'length_max' => '124.9', 'gender' => 'F', 'lt_class' => 'Tall'],
        ], ['age_month', 'length_min', 'length_max', 'gender', 'lt_class']);
    }
}
