<?php

namespace Database\Seeders;

use App\Models\V1\Libraries\LibOccupation;
use Illuminate\Database\Seeder;

class LibOccupationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        LibOccupation::upsert([
            ['code' => 'AGRI001', 'category_code' => 'AGRI', 'occupation_desc' => 'Farmer'],
            ['code' => 'AGRI002', 'category_code' => 'AGRI', 'occupation_desc' => 'Fisherman'],
            ['code' => 'FOOD001', 'category_code' => 'FOOD', 'occupation_desc' => 'Supervisor'],
            ['code' => 'FOOD002', 'category_code' => 'FOOD', 'occupation_desc' => 'Service Engineer'],
            ['code' => 'FOOD003', 'category_code' => 'FOOD', 'occupation_desc' => 'Engineer'],
            ['code' => 'FOOD004', 'category_code' => 'FOOD', 'occupation_desc' => 'Accountant'],
            ['code' => 'GOVT', 'category_code' => 'GOVT', 'occupation_desc' => 'Govt Employee'],
            ['code' => 'GOVT001', 'category_code' => 'GOVT', 'occupation_desc' => 'Employee'],
            ['code' => 'GOVT002', 'category_code' => 'GOVT', 'occupation_desc' => 'Public School Teacher'],
            ['code' => 'HEALTH001', 'category_code' => 'HEALTH', 'occupation_desc' => 'Physician'],
            ['code' => 'HEALTH002', 'category_code' => 'HEALTH', 'occupation_desc' => 'Nurse'],
            ['code' => 'HEALTH003', 'category_code' => 'HEALTH', 'occupation_desc' => 'Midwife'],
            ['code' => 'HEALTH004', 'category_code' => 'HEALTH', 'occupation_desc' => 'Physical Therapist'],
            ['code' => 'HEALTH005', 'category_code' => 'HEALTH', 'occupation_desc' => 'Respiratory Therapist'],
            ['code' => 'HEALTH006', 'category_code' => 'HEALTH', 'occupation_desc' => 'X-Ray Technician'],
            ['code' => 'HEALTH007', 'category_code' => 'HEALTH', 'occupation_desc' => 'Nurse Aide'],
            ['code' => 'HEALTH008', 'category_code' => 'HEALTH', 'occupation_desc' => 'Dentist'],
            ['code' => 'HEALTH009', 'category_code' => 'HEALTH', 'occupation_desc' => 'Medical Technologist'],
            ['code' => 'HEALTH010', 'category_code' => 'HEALTH', 'occupation_desc' => 'Pharmacist'],
            ['code' => 'HEALTH011', 'category_code' => 'HEALTH', 'occupation_desc' => 'Dental Technician'],
            ['code' => 'HEALTH012', 'category_code' => 'HEALTH', 'occupation_desc' => 'Reflexologist'],
            ['code' => 'HEALTH013', 'category_code' => 'HEALTH', 'occupation_desc' => 'Pharmacist Aide'],
            ['code' => 'HEALTH014', 'category_code' => 'HEALTH', 'occupation_desc' => 'Paramedic'],
            ['code' => 'HEALTH015', 'category_code' => 'HEALTH', 'occupation_desc' => 'Caregiver'],
            ['code' => 'MAR001', 'category_code' => 'MAR', 'occupation_desc' => 'Seaman'],
            ['code' => 'MFG001', 'category_code' => 'MFG', 'occupation_desc' => 'Merchandiser'],
            ['code' => 'RETL001', 'category_code' => 'RETL', 'occupation_desc' => 'Vendor'],
            ['code' => 'RETL002', 'category_code' => 'RETL', 'occupation_desc' => 'Promo Girl'],
            ['code' => 'RETL003', 'category_code' => 'RETL', 'occupation_desc' => 'Cashier'],
            ['code' => 'SVC 24', 'category_code' => 'SVC', 'occupation_desc' => 'Janitor'],
            ['code' => 'SVC001', 'category_code' => 'SVC', 'occupation_desc' => 'Employee'],
            ['code' => 'SVC002', 'category_code' => 'SVC', 'occupation_desc' => 'Private School Teacher'],
            ['code' => 'SVC003', 'category_code' => 'SVC', 'occupation_desc' => 'Saleslady'],
            ['code' => 'SVC004', 'category_code' => 'SVC', 'occupation_desc' => 'Barber'],
            ['code' => 'SVC005', 'category_code' => 'SVC', 'occupation_desc' => 'Masseur'],
            ['code' => 'SVC006', 'category_code' => 'SVC', 'occupation_desc' => 'Factory Worker'],
            ['code' => 'SVC007', 'category_code' => 'SVC', 'occupation_desc' => 'Painter'],
            ['code' => 'SVC008', 'category_code' => 'SVC', 'occupation_desc' => 'Welder'],
            ['code' => 'SVC009', 'category_code' => 'SVC', 'occupation_desc' => 'Beautician'],
            ['code' => 'SVC010', 'category_code' => 'SVC', 'occupation_desc' => 'Laundrywoman'],
            ['code' => 'SVC011', 'category_code' => 'SVC', 'occupation_desc' => 'Cook'],
            ['code' => 'SVC012', 'category_code' => 'SVC', 'occupation_desc' => 'Guest Relations Officer'],
            ['code' => 'SVC013', 'category_code' => 'SVC', 'occupation_desc' => 'Streetsweeper'],
            ['code' => 'SVC014', 'category_code' => 'SVC', 'occupation_desc' => 'Garbage collector'],
            ['code' => 'SVC015', 'category_code' => 'SVC', 'occupation_desc' => 'Messenger'],
            ['code' => 'SVC016', 'category_code' => 'SVC', 'occupation_desc' => 'Social Worker'],
            ['code' => 'SVC017', 'category_code' => 'SVC', 'occupation_desc' => 'Laborer, skilled'],
            ['code' => 'SVC018', 'category_code' => 'SVC', 'occupation_desc' => 'Laborer, unskilled'],
            ['code' => 'SVC019', 'category_code' => 'SVC', 'occupation_desc' => 'Security Guard'],
            ['code' => 'SVC020', 'category_code' => 'SVC', 'occupation_desc' => 'Service Crew'],
            ['code' => 'SVC021', 'category_code' => 'SVC', 'occupation_desc' => 'Housemaid'],
            ['code' => 'SVC022', 'category_code' => 'SVC', 'occupation_desc' => 'Family Driver'],
            ['code' => 'SVC023', 'category_code' => 'SVC', 'occupation_desc' => 'Company Driver'],
            ['code' => 'SVC024', 'category_code' => 'SVC', 'occupation_desc' => 'Salesman'],
            ['code' => 'SVC025', 'category_code' => 'SVC', 'occupation_desc' => 'Carpenter'],
            ['code' => 'SVC026', 'category_code' => 'SVC', 'occupation_desc' => 'Gardener'],
            ['code' => 'SVC027', 'category_code' => 'SVC', 'occupation_desc' => 'Actor'],
            ['code' => 'SVC028', 'category_code' => 'SVC', 'occupation_desc' => 'Actress'],
            ['code' => 'SVC029', 'category_code' => 'SVC', 'occupation_desc' => 'Bartender'],
            ['code' => 'SVC030', 'category_code' => 'SVC', 'occupation_desc' => 'Policeman'],
            ['code' => 'SVC031', 'category_code' => 'SVC', 'occupation_desc' => 'Policewoman'],
            ['code' => 'SVC032', 'category_code' => 'SVC', 'occupation_desc' => 'Soldier'],
            ['code' => 'SVC033', 'category_code' => 'SVC', 'occupation_desc' => 'Macho Dancer'],
            ['code' => 'SVC034', 'category_code' => 'SVC', 'occupation_desc' => 'Bouncer'],
            ['code' => 'SVC035', 'category_code' => 'SVC', 'occupation_desc' => 'Aircon Technician'],
            ['code' => 'SVC036', 'category_code' => 'SVC', 'occupation_desc' => 'Waiter'],
            ['code' => 'SVC037', 'category_code' => 'SVC', 'occupation_desc' => 'Butcher'],
            ['code' => 'SVC038', 'category_code' => 'SVC', 'occupation_desc' => 'Artist'],
            ['code' => 'SVC039', 'category_code' => 'SVC', 'occupation_desc' => 'Technician'],
            ['code' => 'SVC040', 'category_code' => 'SVC', 'occupation_desc' => 'Dispatcher'],
            ['code' => 'SVC041', 'category_code' => 'SVC', 'occupation_desc' => 'Electrician'],
            ['code' => 'SVC042', 'category_code' => 'SVC', 'occupation_desc' => 'Machine Operator'],
            ['code' => 'SVC043', 'category_code' => 'SVC', 'occupation_desc' => 'Mason'],
            ['code' => 'SVC044', 'category_code' => 'SVC', 'occupation_desc' => 'Fireman'],
            ['code' => 'SVC045', 'category_code' => 'SVC', 'occupation_desc' => 'Domestic Helper'],
            ['code' => 'SVC046', 'category_code' => 'SVC', 'occupation_desc' => 'Roomboy'],
            ['code' => 'SVC047', 'category_code' => 'SVC', 'occupation_desc' => 'OFW'],
            ['code' => 'SVC048', 'category_code' => 'SVC', 'occupation_desc' => 'Entertainer'],
            ['code' => 'SVC049', 'category_code' => 'SVC', 'occupation_desc' => 'Helper'],
            ['code' => 'SVC050', 'category_code' => 'SVC', 'occupation_desc' => 'Manager'],
            ['code' => 'SVC051', 'category_code' => 'SVC', 'occupation_desc' => 'Clerk'],
            ['code' => 'SVC052', 'category_code' => 'SVC', 'occupation_desc' => 'Administrator'],
            ['code' => 'SVC053', 'category_code' => 'SVC', 'occupation_desc' => 'Sewer'],
            ['code' => 'TRANS001', 'category_code' => 'TRANS', 'occupation_desc' => 'Jeepney Driver'],
            ['code' => 'TRANS002', 'category_code' => 'TRANS', 'occupation_desc' => 'Taxi Driver'],
            ['code' => 'TRANS003', 'category_code' => 'TRANS', 'occupation_desc' => 'Bus Driver'],
            ['code' => 'TRANS004', 'category_code' => 'TRANS', 'occupation_desc' => 'Truck Driver'],
            ['code' => 'TRANS005', 'category_code' => 'TRANS', 'occupation_desc' => 'Bus Conductor'],
            ['code' => 'TRANS006', 'category_code' => 'TRANS', 'occupation_desc' => 'Tricycle Driver'],
            ['code' => 'TRANS007', 'category_code' => 'TRANS', 'occupation_desc' => 'Pedicab Driver'],
            ['code' => 'TRANS008', 'category_code' => 'TRANS', 'occupation_desc' => 'Calesa Driver'],
            ['code' => 'TRANS009', 'category_code' => 'TRANS', 'occupation_desc' => 'Ambulance Driver'],
            ['code' => 'UNSP', 'category_code' => 'UNSP', 'occupation_desc' => 'Housewife'],
            ['code' => 'UNSP001', 'category_code' => 'UNSP', 'occupation_desc' => 'Unspecified'],
            ['code' => 'UNSP002', 'category_code' => 'UNSP', 'occupation_desc' => 'Businessman'],
            ['code' => 'UNSP003', 'category_code' => 'UNSP', 'occupation_desc' => 'Retired'],
            ['code' => 'UNSP004', 'category_code' => 'UNSP', 'occupation_desc' => 'Student'],
            ['code' => 'UNSP005', 'category_code' => 'UNSP', 'occupation_desc' => 'Photograper'],
            ['code' => 'UNSP006', 'category_code' => 'UNSP', 'occupation_desc' => 'None'],
        ], ['occupation_desc']);
    }
}
