<?php

namespace Database\Seeders;

use App\Models\V1\Libraries\LibWeightForAge;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class LibWeightForAgeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        LibWeightForAge::truncate();
        LibWeightForAge::upsert([
            ['age_month' => '0', 'weight_min' => '2.1', 'weight_max' => '2.1', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '0', 'weight_min' => '2.2', 'weight_max' => '2.4', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '0', 'weight_min' => '2.5', 'weight_max' => '4.4', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '0', 'weight_min' => '4.5', 'weight_max' => '4.5', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '1', 'weight_min' => '2.9', 'weight_max' => '2.9', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '1', 'weight_min' => '3.0', 'weight_max' => '3.3', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '1', 'weight_min' => '3.4', 'weight_max' => '5.8', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '1', 'weight_min' => '5.9', 'weight_max' => '5.9', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '2', 'weight_min' => '3.8', 'weight_max' => '3.8', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '2', 'weight_min' => '3.9', 'weight_max' => '4.2', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '2', 'weight_min' => '4.3', 'weight_max' => '7.1', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '2', 'weight_min' => '7.2', 'weight_max' => '7.2', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '3', 'weight_min' => '4.4', 'weight_max' => '4.4', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '3', 'weight_min' => '4.5', 'weight_max' => '4.9', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '3', 'weight_min' => '5.0', 'weight_max' => '8.0', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '3', 'weight_min' => '8.1', 'weight_max' => '8.1', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '4', 'weight_min' => '4.9', 'weight_max' => '4.9', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '4', 'weight_min' => '5.0', 'weight_max' => '5.5', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '4', 'weight_min' => '5.6', 'weight_max' => '8.7', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '4', 'weight_min' => '8.8', 'weight_max' => '8.8', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '5', 'weight_min' => '5.3', 'weight_max' => '5.3', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '5', 'weight_min' => '5.4', 'weight_max' => '5.9', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '5', 'weight_min' => '6.0', 'weight_max' => '9.3', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '5', 'weight_min' => '9.4', 'weight_max' => '9.4', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '6', 'weight_min' => '5.7', 'weight_max' => '5.7', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '6', 'weight_min' => '5.8', 'weight_max' => '6.3', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '6', 'weight_min' => '6.4', 'weight_max' => '9.8', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '6', 'weight_min' => '9.9', 'weight_max' => '9.9', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '7', 'weight_min' => '5.9', 'weight_max' => '5.9', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '7', 'weight_min' => '6.0', 'weight_max' => '6.6', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '7', 'weight_min' => '6.7', 'weight_max' => '10.3', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '7', 'weight_min' => '10.4', 'weight_max' => '10.4', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '8', 'weight_min' => '6.2', 'weight_max' => '6.2', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '8', 'weight_min' => '6.3', 'weight_max' => '6.8', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '8', 'weight_min' => '6.9', 'weight_max' => '10.7', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '8', 'weight_min' => '10.8', 'weight_max' => '10.8', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '9', 'weight_min' => '6.4', 'weight_max' => '6.4', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '9', 'weight_min' => '6.5', 'weight_max' => '7.0', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '9', 'weight_min' => '7.1', 'weight_max' => '11.0', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '9', 'weight_min' => '11.1', 'weight_max' => '11.1', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '10', 'weight_min' => '6.6', 'weight_max' => '6.6', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '10', 'weight_min' => '6.7', 'weight_max' => '7.3', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '10', 'weight_min' => '7.4', 'weight_max' => '11.4', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '10', 'weight_min' => '11.5', 'weight_max' => '11.5', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '11', 'weight_min' => '6.8', 'weight_max' => '6.8', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '11', 'weight_min' => '6.9', 'weight_max' => '7.5', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '11', 'weight_min' => '7.6', 'weight_max' => '11.7', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '11', 'weight_min' => '11.8', 'weight_max' => '11.8', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '12', 'weight_min' => '6.9', 'weight_max' => '6.9', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '12', 'weight_min' => '7.0', 'weight_max' => '7.6', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '12', 'weight_min' => '7.7', 'weight_max' => '12.0', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '12', 'weight_min' => '12.1', 'weight_max' => '12.1', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '13', 'weight_min' => '7.1', 'weight_max' => '7.1', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '13', 'weight_min' => '7.2', 'weight_max' => '7.8', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '13', 'weight_min' => '7.9', 'weight_max' => '12.3', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '13', 'weight_min' => '12.4', 'weight_max' => '12.4', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '14', 'weight_min' => '7.2', 'weight_max' => '7.2', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '14', 'weight_min' => '7.3', 'weight_max' => '8.0', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '14', 'weight_min' => '8.1', 'weight_max' => '12.6', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '14', 'weight_min' => '12.7', 'weight_max' => '12.7', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '15', 'weight_min' => '7.4', 'weight_max' => '7.4', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '15', 'weight_min' => '7.5', 'weight_max' => '8.2', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '15', 'weight_min' => '8.3', 'weight_max' => '12.8', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '15', 'weight_min' => '12.9', 'weight_max' => '12.9', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '16', 'weight_min' => '7.5', 'weight_max' => '7.5', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '16', 'weight_min' => '7.6', 'weight_max' => '8.3', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '16', 'weight_min' => '8.4', 'weight_max' => '13.1', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '16', 'weight_min' => '13.2', 'weight_max' => '13.2', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '17', 'weight_min' => '7.7', 'weight_max' => '7.7', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '17', 'weight_min' => '7.8', 'weight_max' => '8.5', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '17', 'weight_min' => '8.6', 'weight_max' => '13.4', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '17', 'weight_min' => '13.5', 'weight_max' => '13.5', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '18', 'weight_min' => '7.8', 'weight_max' => '7.8', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '18', 'weight_min' => '7.9', 'weight_max' => '8.7', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '18', 'weight_min' => '8.8', 'weight_max' => '13.7', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '18', 'weight_min' => '13.8', 'weight_max' => '13.8', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '19', 'weight_min' => '8.0', 'weight_max' => '8.0', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '19', 'weight_min' => '8.1', 'weight_max' => '8.8', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '19', 'weight_min' => '8.9', 'weight_max' => '13.9', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '19', 'weight_min' => '14.0', 'weight_max' => '14.0', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '20', 'weight_min' => '8.1', 'weight_max' => '8.1', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '20', 'weight_min' => '8.2', 'weight_max' => '9.0', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '20', 'weight_min' => '9.1', 'weight_max' => '14.2', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '20', 'weight_min' => '14.3', 'weight_max' => '14.3', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '21', 'weight_min' => '8.2', 'weight_max' => '8.2', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '21', 'weight_min' => '8.3', 'weight_max' => '9.1', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '21', 'weight_min' => '9.2', 'weight_max' => '14.5', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '21', 'weight_min' => '14.6', 'weight_max' => '14.6', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '22', 'weight_min' => '8.4', 'weight_max' => '8.4', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '22', 'weight_min' => '8.5', 'weight_max' => '9.3', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '22', 'weight_min' => '9.4', 'weight_max' => '14.7', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '22', 'weight_min' => '14.8', 'weight_max' => '14.8', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '23', 'weight_min' => '8.5', 'weight_max' => '8.5', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '23', 'weight_min' => '8.6', 'weight_max' => '9.4', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '23', 'weight_min' => '9.5', 'weight_max' => '15.0', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '23', 'weight_min' => '15.1', 'weight_max' => '15.1', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '24', 'weight_min' => '8.6', 'weight_max' => '8.6', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '24', 'weight_min' => '8.7', 'weight_max' => '9.6', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '24', 'weight_min' => '9.7', 'weight_max' => '15.3', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '24', 'weight_min' => '15.4', 'weight_max' => '15.4', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '25', 'weight_min' => '8.8', 'weight_max' => '8.8', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '25', 'weight_min' => '8.9', 'weight_max' => '9.7', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '25', 'weight_min' => '9.8', 'weight_max' => '15.5', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '25', 'weight_min' => '15.6', 'weight_max' => '15.6', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '26', 'weight_min' => '8.9', 'weight_max' => '8.9', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '26', 'weight_min' => '9.0', 'weight_max' => '9.9', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '26', 'weight_min' => '10.0', 'weight_max' => '15.8', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '26', 'weight_min' => '15.9', 'weight_max' => '15.9', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '27', 'weight_min' => '9.0', 'weight_max' => '9.0', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '27', 'weight_min' => '9.1', 'weight_max' => '10.0', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '27', 'weight_min' => '10.1', 'weight_max' => '16.1', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '27', 'weight_min' => '16.2', 'weight_max' => '16.2', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '28', 'weight_min' => '9.1', 'weight_max' => '9.1', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '28', 'weight_min' => '9.2', 'weight_max' => '10.1', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '28', 'weight_min' => '10.2', 'weight_max' => '16.3', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '28', 'weight_min' => '16.4', 'weight_max' => '16.4', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '29', 'weight_min' => '9.2', 'weight_max' => '9.2', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '29', 'weight_min' => '9.3', 'weight_max' => '10.3', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '29', 'weight_min' => '10.4', 'weight_max' => '16.6', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '29', 'weight_min' => '16.7', 'weight_max' => '16.7', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '30', 'weight_min' => '9.4', 'weight_max' => '9.4', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '30', 'weight_min' => '9.5', 'weight_max' => '10.4', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '30', 'weight_min' => '10.5', 'weight_max' => '16.9', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '30', 'weight_min' => '17.0', 'weight_max' => '17.0', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '31', 'weight_min' => '9.5', 'weight_max' => '9.5', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '31', 'weight_min' => '9.6', 'weight_max' => '10.6', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '31', 'weight_min' => '10.7', 'weight_max' => '17.1', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '31', 'weight_min' => '17.2', 'weight_max' => '17.2', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '32', 'weight_min' => '9.6', 'weight_max' => '9.6', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '32', 'weight_min' => '9.7', 'weight_max' => '10.7', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '32', 'weight_min' => '10.8', 'weight_max' => '17.4', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '32', 'weight_min' => '17.5', 'weight_max' => '17.5', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '33', 'weight_min' => '9.7', 'weight_max' => '9.7', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '33', 'weight_min' => '9.8', 'weight_max' => '10.8', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '33', 'weight_min' => '10.9', 'weight_max' => '17.6', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '33', 'weight_min' => '17.7', 'weight_max' => '17.7', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '34', 'weight_min' => '9.8', 'weight_max' => '9.8', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '34', 'weight_min' => '9.9', 'weight_max' => '10.9', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '34', 'weight_min' => '11.0', 'weight_max' => '17.8', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '34', 'weight_min' => '17.9', 'weight_max' => '17.9', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '35', 'weight_min' => '9.8', 'weight_max' => '9.8', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '35', 'weight_min' => '9.9', 'weight_max' => '10.9', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '35', 'weight_min' => '11.0', 'weight_max' => '17.8', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '35', 'weight_min' => '17.9', 'weight_max' => '17.9', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '36', 'weight_min' => '10.0', 'weight_max' => '10.0', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '36', 'weight_min' => '10.1', 'weight_max' => '11.2', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '36', 'weight_min' => '11.3', 'weight_max' => '18.3', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '36', 'weight_min' => '18.4', 'weight_max' => '18.4', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '37', 'weight_min' => '10.1', 'weight_max' => '10.1', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '37', 'weight_min' => '10.2', 'weight_max' => '11.3', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '37', 'weight_min' => '11.4', 'weight_max' => '18.6', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '37', 'weight_min' => '18.7', 'weight_max' => '18.7', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '38', 'weight_min' => '10.2', 'weight_max' => '10.2', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '38', 'weight_min' => '10.3', 'weight_max' => '11.4', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '38', 'weight_min' => '11.5', 'weight_max' => '18.8', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '38', 'weight_min' => '18.9', 'weight_max' => '18.9', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '39', 'weight_min' => '10.3', 'weight_max' => '10.3', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '39', 'weight_min' => '10.4', 'weight_max' => '11.5', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '39', 'weight_min' => '11.6', 'weight_max' => '19.0', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '39', 'weight_min' => '19.1', 'weight_max' => '19.1', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '40', 'weight_min' => '10.4', 'weight_max' => '10.4', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '40', 'weight_min' => '10.5', 'weight_max' => '11.7', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '40', 'weight_min' => '11.8', 'weight_max' => '19.3', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '40', 'weight_min' => '19.4', 'weight_max' => '19.4', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '41', 'weight_min' => '10.5', 'weight_max' => '10.5', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '41', 'weight_min' => '10.6', 'weight_max' => '11.8', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '41', 'weight_min' => '11.9', 'weight_max' => '19.5', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '41', 'weight_min' => '19.6', 'weight_max' => '19.6', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '42', 'weight_min' => '10.6', 'weight_max' => '10.6', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '42', 'weight_min' => '10.7', 'weight_max' => '11.9', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '42', 'weight_min' => '12.0', 'weight_max' => '19.7', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '42', 'weight_min' => '19.8', 'weight_max' => '19.8', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '43', 'weight_min' => '10.7', 'weight_max' => '10.7', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '43', 'weight_min' => '10.8', 'weight_max' => '12.0', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '43', 'weight_min' => '12.1', 'weight_max' => '20.0', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '43', 'weight_min' => '20.1', 'weight_max' => '20.1', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '44', 'weight_min' => '10.8', 'weight_max' => '10.8', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '44', 'weight_min' => '10.9', 'weight_max' => '12.1', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '44', 'weight_min' => '12.2', 'weight_max' => '20.2', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '44', 'weight_min' => '20.3', 'weight_max' => '20.3', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '45', 'weight_min' => '10.9', 'weight_max' => '10.9', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '45', 'weight_min' => '11.0', 'weight_max' => '12.3', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '45', 'weight_min' => '12.4', 'weight_max' => '20.5', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '45', 'weight_min' => '20.6', 'weight_max' => '20.6', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '46', 'weight_min' => '11.0', 'weight_max' => '11.0', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '46', 'weight_min' => '11.1', 'weight_max' => '12.4', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '46', 'weight_min' => '12.5', 'weight_max' => '20.7', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '46', 'weight_min' => '20.8', 'weight_max' => '20.8', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '47', 'weight_min' => '11.1', 'weight_max' => '11.1', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '47', 'weight_min' => '11.2', 'weight_max' => '12.5', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '47', 'weight_min' => '12.6', 'weight_max' => '20.9', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '47', 'weight_min' => '21.0', 'weight_max' => '21.0', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '48', 'weight_min' => '11.2', 'weight_max' => '11.2', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '48', 'weight_min' => '11.3', 'weight_max' => '12.6', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '48', 'weight_min' => '12.7', 'weight_max' => '21.2', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '48', 'weight_min' => '21.3', 'weight_max' => '21.3', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '49', 'weight_min' => '11.3', 'weight_max' => '11.3', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '49', 'weight_min' => '11.4', 'weight_max' => '12.7', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '49', 'weight_min' => '12.8', 'weight_max' => '21.4', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '49', 'weight_min' => '21.5', 'weight_max' => '21.5', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '50', 'weight_min' => '11.4', 'weight_max' => '11.4', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '50', 'weight_min' => '11.5', 'weight_max' => '12.8', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '50', 'weight_min' => '12.9', 'weight_max' => '21.7', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '50', 'weight_min' => '21.8', 'weight_max' => '21.8', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '51', 'weight_min' => '11.5', 'weight_max' => '11.5', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '51', 'weight_min' => '11.6', 'weight_max' => '13.0', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '51', 'weight_min' => '13.1', 'weight_max' => '21.9', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '51', 'weight_min' => '22.0', 'weight_max' => '22.0', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '52', 'weight_min' => '11.6', 'weight_max' => '11.6', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '52', 'weight_min' => '11.7', 'weight_max' => '13.1', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '52', 'weight_min' => '13.2', 'weight_max' => '22.2', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '52', 'weight_min' => '22.3', 'weight_max' => '22.3', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '53', 'weight_min' => '11.7', 'weight_max' => '11.7', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '53', 'weight_min' => '11.8', 'weight_max' => '13.2', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '53', 'weight_min' => '13.3', 'weight_max' => '22.4', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '53', 'weight_min' => '22.5', 'weight_max' => '22.5', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '54', 'weight_min' => '11.8', 'weight_max' => '11.8', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '54', 'weight_min' => '11.9', 'weight_max' => '13.3', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '54', 'weight_min' => '13.4', 'weight_max' => '22.7', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '54', 'weight_min' => '22.8', 'weight_max' => '22.8', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '55', 'weight_min' => '11.9', 'weight_max' => '11.9', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '55', 'weight_min' => '12.0', 'weight_max' => '13.4', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '55', 'weight_min' => '13.5', 'weight_max' => '22.9', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '55', 'weight_min' => '23.0', 'weight_max' => '23.0', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '56', 'weight_min' => '12.0', 'weight_max' => '12.0', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '56', 'weight_min' => '12.1', 'weight_max' => '13.5', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '56', 'weight_min' => '13.6', 'weight_max' => '23.2', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '56', 'weight_min' => '23.3', 'weight_max' => '23.3', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '57', 'weight_min' => '12.1', 'weight_max' => '12.1', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '57', 'weight_min' => '12.2', 'weight_max' => '13.6', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '57', 'weight_min' => '13.7', 'weight_max' => '23.4', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '57', 'weight_min' => '23.5', 'weight_max' => '23.5', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '58', 'weight_min' => '12.2', 'weight_max' => '12.2', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '58', 'weight_min' => '12.3', 'weight_max' => '13.7', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '58', 'weight_min' => '13.8', 'weight_max' => '23.7', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '58', 'weight_min' => '23.8', 'weight_max' => '23.8', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '59', 'weight_min' => '12.3', 'weight_max' => '12.3', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '59', 'weight_min' => '12.4', 'weight_max' => '13.9', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '59', 'weight_min' => '14.0', 'weight_max' => '23.9', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '59', 'weight_min' => '24.0', 'weight_max' => '24.0', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '60', 'weight_min' => '12.4', 'weight_max' => '12.4', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '60', 'weight_min' => '12.5', 'weight_max' => '14.0', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '60', 'weight_min' => '14.1', 'weight_max' => '24.2', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '60', 'weight_min' => '24.3', 'weight_max' => '24.3', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '61', 'weight_min' => '12.7', 'weight_max' => '12.7', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '61', 'weight_min' => '12.8', 'weight_max' => '14.3', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '61', 'weight_min' => '14.4', 'weight_max' => '24.3', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '61', 'weight_min' => '24.4', 'weight_max' => '24.4', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '62', 'weight_min' => '12.8', 'weight_max' => '12.8', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '62', 'weight_min' => '12.9', 'weight_max' => '14.4', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '62', 'weight_min' => '14.5', 'weight_max' => '24.4', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '62', 'weight_min' => '24.5', 'weight_max' => '24.5', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '63', 'weight_min' => '13.0', 'weight_max' => '13.0', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '63', 'weight_min' => '13.1', 'weight_max' => '14.5', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '63', 'weight_min' => '14.6', 'weight_max' => '24.7', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '63', 'weight_min' => '24.8', 'weight_max' => '24.8', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '64', 'weight_min' => '13.1', 'weight_max' => '13.1', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '64', 'weight_min' => '13.2', 'weight_max' => '14.7', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '64', 'weight_min' => '14.8', 'weight_max' => '24.9', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '64', 'weight_min' => '25.0', 'weight_max' => '25.0', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '65', 'weight_min' => '13.2', 'weight_max' => '13.2', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '65', 'weight_min' => '13.3', 'weight_max' => '14.8', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '65', 'weight_min' => '14.9', 'weight_max' => '25.2', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '65', 'weight_min' => '25.3', 'weight_max' => '25.3', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '66', 'weight_min' => '13.3', 'weight_max' => '13.3', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '66', 'weight_min' => '13.4', 'weight_max' => '14.9', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '66', 'weight_min' => '15.0', 'weight_max' => '25.5', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '66', 'weight_min' => '25.6', 'weight_max' => '25.6', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '67', 'weight_min' => '13.4', 'weight_max' => '13.4', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '67', 'weight_min' => '13.5', 'weight_max' => '15.1', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '67', 'weight_min' => '15.2', 'weight_max' => '25.7', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '67', 'weight_min' => '25.8', 'weight_max' => '25.8', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '68', 'weight_min' => '13.6', 'weight_max' => '13.6', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '68', 'weight_min' => '13.7', 'weight_max' => '15.2', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '68', 'weight_min' => '15.3', 'weight_max' => '26.0', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '68', 'weight_min' => '26.1', 'weight_max' => '26.1', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '69', 'weight_min' => '13.7', 'weight_max' => '13.7', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '69', 'weight_min' => '13.8', 'weight_max' => '15.3', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '69', 'weight_min' => '15.4', 'weight_max' => '26.3', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '69', 'weight_min' => '26.4', 'weight_max' => '26.4', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '70', 'weight_min' => '13.8', 'weight_max' => '13.8', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '70', 'weight_min' => '13.9', 'weight_max' => '15.5', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '70', 'weight_min' => '15.6', 'weight_max' => '26.6', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '70', 'weight_min' => '26.7', 'weight_max' => '26.7', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '71', 'weight_min' => '13.9', 'weight_max' => '13.9', 'gender' => 'M', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '71', 'weight_min' => '14.0', 'weight_max' => '15.6', 'gender' => 'M', 'wt_class' => 'Underweight'],
            ['age_month' => '71', 'weight_min' => '15.7', 'weight_max' => '26.8', 'gender' => 'M', 'wt_class' => 'Normal'],
            ['age_month' => '71', 'weight_min' => '26.9', 'weight_max' => '26.9', 'gender' => 'M', 'wt_class' => 'Overweight'],
            ['age_month' => '0', 'weight_min' => '2.0', 'weight_max' => '2.0', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '0', 'weight_min' => '2.1', 'weight_max' => '2.3', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '0', 'weight_min' => '2.4', 'weight_max' => '4.2', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '0', 'weight_min' => '4.3', 'weight_max' => '4.3', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '1', 'weight_min' => '2.7', 'weight_max' => '2.7', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '1', 'weight_min' => '2.8', 'weight_max' => '3.1', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '1', 'weight_min' => '3.2', 'weight_max' => '5.5', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '1', 'weight_min' => '5.6', 'weight_max' => '5.6', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '2', 'weight_min' => '3.4', 'weight_max' => '3.4', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '2', 'weight_min' => '3.5', 'weight_max' => '3.8', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '2', 'weight_min' => '3.9', 'weight_max' => '6.6', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '2', 'weight_min' => '6.7', 'weight_max' => '6.7', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '3', 'weight_min' => '4.0', 'weight_max' => '4.0', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '3', 'weight_min' => '4.1', 'weight_max' => '4.4', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '3', 'weight_min' => '4.5', 'weight_max' => '7.5', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '3', 'weight_min' => '7.6', 'weight_max' => '7.6', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '4', 'weight_min' => '4.4', 'weight_max' => '4.4', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '4', 'weight_min' => '4.5', 'weight_max' => '4.9', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '4', 'weight_min' => '5.0', 'weight_max' => '8.2', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '4', 'weight_min' => '8.3', 'weight_max' => '8.3', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '5', 'weight_min' => '4.8', 'weight_max' => '4.8', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '5', 'weight_min' => '4.9', 'weight_max' => '5.3', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '5', 'weight_min' => '5.4', 'weight_max' => '8.8', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '5', 'weight_min' => '8.9', 'weight_max' => '8.9', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '6', 'weight_min' => '5.1', 'weight_max' => '5.1', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '6', 'weight_min' => '5.2', 'weight_max' => '5.6', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '6', 'weight_min' => '5.7', 'weight_max' => '9.3', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '6', 'weight_min' => '9.4', 'weight_max' => '9.4', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '7', 'weight_min' => '5.3', 'weight_max' => '5.3', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '7', 'weight_min' => '5.4', 'weight_max' => '5.9', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '7', 'weight_min' => '6.0', 'weight_max' => '9.8', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '7', 'weight_min' => '9.9', 'weight_max' => '9.9', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '8', 'weight_min' => '5.6', 'weight_max' => '5.6', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '8', 'weight_min' => '5.7', 'weight_max' => '6.2', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '8', 'weight_min' => '6.3', 'weight_max' => '10.2', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '8', 'weight_min' => '10.3', 'weight_max' => '10.3', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '9', 'weight_min' => '5.8', 'weight_max' => '5.8', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '9', 'weight_min' => '5.9', 'weight_max' => '6.4', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '9', 'weight_min' => '6.5', 'weight_max' => '10.5', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '9', 'weight_min' => '10.6', 'weight_max' => '10.6', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '10', 'weight_min' => '5.9', 'weight_max' => '5.9', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '10', 'weight_min' => '6.0', 'weight_max' => '6.6', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '10', 'weight_min' => '6.7', 'weight_max' => '10.9', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '10', 'weight_min' => '11.0', 'weight_max' => '11.0', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '11', 'weight_min' => '6.1', 'weight_max' => '6.1', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '11', 'weight_min' => '6.2', 'weight_max' => '6.8', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '11', 'weight_min' => '6.9', 'weight_max' => '11.2', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '11', 'weight_min' => '11.3', 'weight_max' => '11.3', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '12', 'weight_min' => '6.3', 'weight_max' => '6.3', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '12', 'weight_min' => '6.4', 'weight_max' => '6.9', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '12', 'weight_min' => '7.0', 'weight_max' => '11.5', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '12', 'weight_min' => '11.6', 'weight_max' => '11.6', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '13', 'weight_min' => '6.4', 'weight_max' => '6.4', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '13', 'weight_min' => '6.5', 'weight_max' => '7.1', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '13', 'weight_min' => '7.2', 'weight_max' => '11.8', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '13', 'weight_min' => '11.9', 'weight_max' => '11.9', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '14', 'weight_min' => '6.6', 'weight_max' => '6.6', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '14', 'weight_min' => '6.7', 'weight_max' => '7.3', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '14', 'weight_min' => '7.4', 'weight_max' => '12.1', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '14', 'weight_min' => '12.2', 'weight_max' => '12.2', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '15', 'weight_min' => '6.7', 'weight_max' => '6.7', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '15', 'weight_min' => '6.8', 'weight_max' => '7.5', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '15', 'weight_min' => '7.6', 'weight_max' => '12.4', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '15', 'weight_min' => '12.5', 'weight_max' => '12.5', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '16', 'weight_min' => '6.9', 'weight_max' => '6.9', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '16', 'weight_min' => '7.0', 'weight_max' => '7.6', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '16', 'weight_min' => '7.7', 'weight_max' => '12.6', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '16', 'weight_min' => '12.7', 'weight_max' => '12.7', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '17', 'weight_min' => '7.0', 'weight_max' => '7.0', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '17', 'weight_min' => '7.1', 'weight_max' => '7.8', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '17', 'weight_min' => '7.9', 'weight_max' => '12.9', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '17', 'weight_min' => '13.0', 'weight_max' => '13.0', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '18', 'weight_min' => '7.2', 'weight_max' => '7.2', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '18', 'weight_min' => '7.3', 'weight_max' => '8.0', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '18', 'weight_min' => '8.1', 'weight_max' => '13.2', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '18', 'weight_min' => '13.3', 'weight_max' => '13.3', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '19', 'weight_min' => '7.3', 'weight_max' => '7.3', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '19', 'weight_min' => '7.4', 'weight_max' => '8.1', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '19', 'weight_min' => '8.2', 'weight_max' => '13.5', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '19', 'weight_min' => '13.6', 'weight_max' => '13.6', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '20', 'weight_min' => '7.5', 'weight_max' => '7.5', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '20', 'weight_min' => '7.6', 'weight_max' => '8.3', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '20', 'weight_min' => '8.4', 'weight_max' => '13.7', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '20', 'weight_min' => '13.8', 'weight_max' => '13.8', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '21', 'weight_min' => '7.6', 'weight_max' => '7.6', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '21', 'weight_min' => '7.7', 'weight_max' => '8.5', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '21', 'weight_min' => '8.6', 'weight_max' => '14.0', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '21', 'weight_min' => '14.1', 'weight_max' => '14.1', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '22', 'weight_min' => '7.8', 'weight_max' => '7.8', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '22', 'weight_min' => '7.9', 'weight_max' => '8.6', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '22', 'weight_min' => '8.7', 'weight_max' => '14.3', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '22', 'weight_min' => '14.4', 'weight_max' => '14.4', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '23', 'weight_min' => '7.9', 'weight_max' => '7.9', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '23', 'weight_min' => '8.0', 'weight_max' => '8.8', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '23', 'weight_min' => '8.9', 'weight_max' => '14.6', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '23', 'weight_min' => '14.7', 'weight_max' => '14.7', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '24', 'weight_min' => '8.1', 'weight_max' => '8.1', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '24', 'weight_min' => '8.2', 'weight_max' => '8.9', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '24', 'weight_min' => '9.0', 'weight_max' => '14.8', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '24', 'weight_min' => '14.9', 'weight_max' => '14.9', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '25', 'weight_min' => '8.2', 'weight_max' => '8.2', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '25', 'weight_min' => '8.3', 'weight_max' => '9.1', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '25', 'weight_min' => '9.2', 'weight_max' => '15.1', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '25', 'weight_min' => '15.2', 'weight_max' => '15.2', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '26', 'weight_min' => '8.4', 'weight_max' => '8.4', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '26', 'weight_min' => '8.5', 'weight_max' => '9.3', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '26', 'weight_min' => '9.4', 'weight_max' => '15.4', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '26', 'weight_min' => '15.5', 'weight_max' => '15.5', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '27', 'weight_min' => '8.5', 'weight_max' => '8.5', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '27', 'weight_min' => '8.6', 'weight_max' => '9.4', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '27', 'weight_min' => '9.5', 'weight_max' => '15.7', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '27', 'weight_min' => '15.8', 'weight_max' => '15.8', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '28', 'weight_min' => '8.6', 'weight_max' => '8.6', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '28', 'weight_min' => '8.7', 'weight_max' => '9.6', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '28', 'weight_min' => '9.7', 'weight_max' => '16.0', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '28', 'weight_min' => '16.1', 'weight_max' => '16.1', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '29', 'weight_min' => '8.8', 'weight_max' => '8.8', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '29', 'weight_min' => '8.9', 'weight_max' => '9.7', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '29', 'weight_min' => '9.8', 'weight_max' => '16.2', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '29', 'weight_min' => '16.3', 'weight_max' => '16.3', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '30', 'weight_min' => '8.9', 'weight_max' => '8.9', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '30', 'weight_min' => '9.0', 'weight_max' => '9.9', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '30', 'weight_min' => '10.0', 'weight_max' => '16.5', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '30', 'weight_min' => '16.6', 'weight_max' => '16.6', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '31', 'weight_min' => '9.0', 'weight_max' => '9.0', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '31', 'weight_min' => '9.1', 'weight_max' => '10.0', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '31', 'weight_min' => '10.1', 'weight_max' => '16.8', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '31', 'weight_min' => '16.9', 'weight_max' => '16.9', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '32', 'weight_min' => '9.1', 'weight_max' => '9.1', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '32', 'weight_min' => '9.2', 'weight_max' => '10.2', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '32', 'weight_min' => '10.3', 'weight_max' => '17.1', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '32', 'weight_min' => '17.2', 'weight_max' => '17.2', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '33', 'weight_min' => '9.3', 'weight_max' => '9.3', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '33', 'weight_min' => '9.4', 'weight_max' => '10.3', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '33', 'weight_min' => '10.4', 'weight_max' => '17.3', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '33', 'weight_min' => '17.4', 'weight_max' => '17.4', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '34', 'weight_min' => '9.4', 'weight_max' => '9.4', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '34', 'weight_min' => '9.5', 'weight_max' => '10.4', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '34', 'weight_min' => '10.5', 'weight_max' => '17.6', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '34', 'weight_min' => '17.7', 'weight_max' => '17.7', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '35', 'weight_min' => '9.5', 'weight_max' => '9.5', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '35', 'weight_min' => '9.6', 'weight_max' => '10.6', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '35', 'weight_min' => '10.7', 'weight_max' => '17.9', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '35', 'weight_min' => '18.0', 'weight_max' => '18.0', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '36', 'weight_min' => '9.6', 'weight_max' => '9.6', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '36', 'weight_min' => '9.7', 'weight_max' => '10.7', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '36', 'weight_min' => '10.8', 'weight_max' => '18.1', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '36', 'weight_min' => '18.2', 'weight_max' => '18.2', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '37', 'weight_min' => '9.7', 'weight_max' => '9.7', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '37', 'weight_min' => '9.8', 'weight_max' => '10.8', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '37', 'weight_min' => '10.9', 'weight_max' => '18.4', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '37', 'weight_min' => '18.4', 'weight_max' => '18.4', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '38', 'weight_min' => '9.8', 'weight_max' => '9.8', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '38', 'weight_min' => '9.9', 'weight_max' => '11.0', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '38', 'weight_min' => '11.1', 'weight_max' => '18.7', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '38', 'weight_min' => '18.8', 'weight_max' => '18.8', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '39', 'weight_min' => '9.9', 'weight_max' => '9.9', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '39', 'weight_min' => '10.0', 'weight_max' => '11.1', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '39', 'weight_min' => '11.2', 'weight_max' => '19.0', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '39', 'weight_min' => '19.1', 'weight_max' => '19.1', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '40', 'weight_min' => '10.1', 'weight_max' => '10.1', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '40', 'weight_min' => '10.2', 'weight_max' => '11.2', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '40', 'weight_min' => '11.3', 'weight_max' => '19.2', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '40', 'weight_min' => '19.3', 'weight_max' => '19.3', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '41', 'weight_min' => '10.2', 'weight_max' => '10.2', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '41', 'weight_min' => '10.3', 'weight_max' => '11.4', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '41', 'weight_min' => '11.5', 'weight_max' => '19.5', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '41', 'weight_min' => '19.6', 'weight_max' => '19.6', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '42', 'weight_min' => '10.3', 'weight_max' => '10.3', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '42', 'weight_min' => '10.4', 'weight_max' => '11.5', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '42', 'weight_min' => '11.6', 'weight_max' => '19.8', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '42', 'weight_min' => '19.9', 'weight_max' => '19.9', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '43', 'weight_min' => '10.4', 'weight_max' => '10.4', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '43', 'weight_min' => '10.5', 'weight_max' => '11.6', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '43', 'weight_min' => '11.7', 'weight_max' => '20.1', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '43', 'weight_min' => '20.2', 'weight_max' => '20.2', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '44', 'weight_min' => '10.5', 'weight_max' => '10.5', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '44', 'weight_min' => '10.6', 'weight_max' => '11.7', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '44', 'weight_min' => '11.8', 'weight_max' => '20.4', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '44', 'weight_min' => '20.5', 'weight_max' => '20.5', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '45', 'weight_min' => '10.6', 'weight_max' => '10.6', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '45', 'weight_min' => '10.7', 'weight_max' => '11.9', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '45', 'weight_min' => '12.0', 'weight_max' => '20.7', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '45', 'weight_min' => '20.8', 'weight_max' => '20.8', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '46', 'weight_min' => '10.7', 'weight_max' => '10.7', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '46', 'weight_min' => '10.8', 'weight_max' => '12.0', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '46', 'weight_min' => '12.1', 'weight_max' => '20.9', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '46', 'weight_min' => '21.0', 'weight_max' => '21.0', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '47', 'weight_min' => '10.8', 'weight_max' => '10.8', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '47', 'weight_min' => '10.9', 'weight_max' => '12.1', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '47', 'weight_min' => '12.2', 'weight_max' => '21.2', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '47', 'weight_min' => '21.3', 'weight_max' => '21.3', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '48', 'weight_min' => '10.9', 'weight_max' => '10.9', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '48', 'weight_min' => '11.0', 'weight_max' => '12.2', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '48', 'weight_min' => '12.3', 'weight_max' => '21.5', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '48', 'weight_min' => '21.6', 'weight_max' => '21.6', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '49', 'weight_min' => '11.0', 'weight_max' => '11.0', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '49', 'weight_min' => '11.1', 'weight_max' => '12.3', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '49', 'weight_min' => '12.4', 'weight_max' => '21.8', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '49', 'weight_min' => '21.9', 'weight_max' => '21.9', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '50', 'weight_min' => '11.1', 'weight_max' => '11.1', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '50', 'weight_min' => '11.2', 'weight_max' => '12.4', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '50', 'weight_min' => '12.5', 'weight_max' => '22.1', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '50', 'weight_min' => '22.2', 'weight_max' => '22.2', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '51', 'weight_min' => '11.2', 'weight_max' => '11.2', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '51', 'weight_min' => '11.3', 'weight_max' => '12.6', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '51', 'weight_min' => '12.7', 'weight_max' => '22.4', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '51', 'weight_min' => '22.5', 'weight_max' => '22.5', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '52', 'weight_min' => '11.3', 'weight_max' => '11.3', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '52', 'weight_min' => '11.4', 'weight_max' => '12.7', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '52', 'weight_min' => '12.8', 'weight_max' => '22.6', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '52', 'weight_min' => '22.7', 'weight_max' => '22.7', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '53', 'weight_min' => '11.4', 'weight_max' => '11.4', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '53', 'weight_min' => '11.5', 'weight_max' => '12.8', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '53', 'weight_min' => '12.9', 'weight_max' => '22.9', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '53', 'weight_min' => '23.0', 'weight_max' => '23.0', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '54', 'weight_min' => '11.5', 'weight_max' => '11.5', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '54', 'weight_min' => '11.6', 'weight_max' => '12.9', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '54', 'weight_min' => '13.0', 'weight_max' => '23.2', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '54', 'weight_min' => '23.3', 'weight_max' => '23.3', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '55', 'weight_min' => '11.6', 'weight_max' => '11.6', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '55', 'weight_min' => '11.7', 'weight_max' => '13.1', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '55', 'weight_min' => '13.2', 'weight_max' => '23.5', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '55', 'weight_min' => '23.6', 'weight_max' => '23.6', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '56', 'weight_min' => '11.7', 'weight_max' => '11.7', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '56', 'weight_min' => '11.8', 'weight_max' => '13.2', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '56', 'weight_min' => '13.3', 'weight_max' => '23.8', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '56', 'weight_min' => '23.9', 'weight_max' => '23.9', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '57', 'weight_min' => '11.8', 'weight_max' => '11.8', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '57', 'weight_min' => '11.9', 'weight_max' => '13.3', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '57', 'weight_min' => '13.4', 'weight_max' => '24.1', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '57', 'weight_min' => '23.2', 'weight_max' => '23.2', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '58', 'weight_min' => '11.9', 'weight_max' => '11.9', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '58', 'weight_min' => '12.0', 'weight_max' => '13.4', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '58', 'weight_min' => '13.5', 'weight_max' => '24.4', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '58', 'weight_min' => '24.5', 'weight_max' => '24.5', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '59', 'weight_min' => '12.0', 'weight_max' => '12.0', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '59', 'weight_min' => '12.1', 'weight_max' => '13.5', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '59', 'weight_min' => '13.6', 'weight_max' => '24.6', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '59', 'weight_min' => '24.7', 'weight_max' => '24.7', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '60', 'weight_min' => '12.1', 'weight_max' => '12.1', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '60', 'weight_min' => '12.2', 'weight_max' => '13.6', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '60', 'weight_min' => '13.7', 'weight_max' => '24.7', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '60', 'weight_min' => '24.8', 'weight_max' => '24.8', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '61', 'weight_min' => '12.4', 'weight_max' => '12.4', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '61', 'weight_min' => '12.5', 'weight_max' => '13.9', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '61', 'weight_min' => '14.0', 'weight_max' => '24.8', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '61', 'weight_min' => '24.9', 'weight_max' => '24.9', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '62', 'weight_min' => '12.5', 'weight_max' => '12.5', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '62', 'weight_min' => '12.6', 'weight_max' => '14.0', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '62', 'weight_min' => '14.1', 'weight_max' => '25.1', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '62', 'weight_min' => '25.2', 'weight_max' => '25.2', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '63', 'weight_min' => '12.6', 'weight_max' => '12.6', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '63', 'weight_min' => '12.7', 'weight_max' => '14.1', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '63', 'weight_min' => '14.2', 'weight_max' => '25.4', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '63', 'weight_min' => '25.5', 'weight_max' => '25.5', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '64', 'weight_min' => '12.7', 'weight_max' => '12.7', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '64', 'weight_min' => '12.8', 'weight_max' => '14.2', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '64', 'weight_min' => '14.3', 'weight_max' => '25.6', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '64', 'weight_min' => '25.7', 'weight_max' => '25.7', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '65', 'weight_min' => '12.8', 'weight_max' => '12.8', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '65', 'weight_min' => '12.9', 'weight_max' => '14.3', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '65', 'weight_min' => '14.4', 'weight_max' => '25.9', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '65', 'weight_min' => '26.0', 'weight_max' => '26.0', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '66', 'weight_min' => '12.9', 'weight_max' => '12.9', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '66', 'weight_min' => '13.0', 'weight_max' => '14.5', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '66', 'weight_min' => '14.6', 'weight_max' => '26.2', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '66', 'weight_min' => '26.3', 'weight_max' => '26.3', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '67', 'weight_min' => '13.0', 'weight_max' => '13.0', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '67', 'weight_min' => '13.1', 'weight_max' => '14.6', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '67', 'weight_min' => '14.7', 'weight_max' => '26.5', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '67', 'weight_min' => '26.6', 'weight_max' => '26.6', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '68', 'weight_min' => '13.1', 'weight_max' => '13.1', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '68', 'weight_min' => '13.2', 'weight_max' => '14.7', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '68', 'weight_min' => '14.8', 'weight_max' => '26.7', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '68', 'weight_min' => '26.8', 'weight_max' => '26.8', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '69', 'weight_min' => '13.2', 'weight_max' => '13.2', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '69', 'weight_min' => '13.3', 'weight_max' => '14.8', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '69', 'weight_min' => '14.9', 'weight_max' => '27.0', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '69', 'weight_min' => '27.1', 'weight_max' => '27.1', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '70', 'weight_min' => '13.3', 'weight_max' => '13.3', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '70', 'weight_min' => '13.4', 'weight_max' => '14.9', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '70', 'weight_min' => '15.0', 'weight_max' => '27.3', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '70', 'weight_min' => '27.4', 'weight_max' => '27.4', 'gender' => 'F', 'wt_class' => 'Overweight'],
            ['age_month' => '71', 'weight_min' => '13.4', 'weight_max' => '13.4', 'gender' => 'F', 'wt_class' => 'Severely Underweight'],
            ['age_month' => '71', 'weight_min' => '13.5', 'weight_max' => '15.1', 'gender' => 'F', 'wt_class' => 'Underweight'],
            ['age_month' => '71', 'weight_min' => '15.2', 'weight_max' => '27.6', 'gender' => 'F', 'wt_class' => 'Normal'],
            ['age_month' => '71', 'weight_min' => '27.7', 'weight_max' => '27.7', 'gender' => 'F', 'wt_class' => 'Overweight']
        ], ['age_month', 'weight_min', 'weight_max', 'gender', 'wt_class'], ['age_month', 'weight_min', 'weight_max', 'gender', 'wt_class']);
    }
}
